import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { mkdtempSync, rmSync, mkdirSync, writeFileSync, readFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  analyzeRatings,
  detectPatterns,
  formatSynthesisReport,
  FRUSTRATION_RULES,
  loadRatings,
  main,
  SUCCESS_RULES,
  writeSynthesis,
  type Deps,
  type Rating,
  type SynthesisResult,
} from "./learning-pattern-synthesis";

// ============================================================================
// Reference implementations copied VERBATIM from the origin (~/.claude/PAI/Tools/
// LearningPatternSynthesis.ts) — the byte-parity oracle for the std-substrate rewrite.
// ============================================================================

const FRUSTRATION_PATTERNS: Record<string, RegExp> = {
  "Time/Performance Issues": /time|slow|delay|hang|wait|long|minutes|hours/i,
  "Incomplete Work": /incomplete|missing|partial|didn't finish|not done/i,
  "Wrong Approach": /wrong|incorrect|not what|misunderstand|mistake/i,
  "Over-engineering": /over-?engineer|too complex|unnecessary|bloat/i,
  "Tool/System Failures": /fail|error|broken|crash|bug|issue/i,
  "Communication Problems": /unclear|confus|didn't ask|should have asked/i,
  "Repetitive Issues": /again|repeat|still|same problem/i,
};

const SUCCESS_PATTERNS: Record<string, RegExp> = {
  "Quick Resolution": /quick|fast|efficient|smooth/i,
  "Good Understanding": /understood|clear|exactly|perfect/i,
  "Proactive Help": /proactive|anticipat|helpful|above and beyond/i,
  "Clean Implementation": /clean|simple|elegant|well done/i,
};

function detectPatternsOriginal(summaries: string[], patterns: Record<string, RegExp>): Map<string, string[]> {
  const results = new Map<string, string[]>();
  for (const summary of summaries) {
    for (const [name, pattern] of Object.entries(patterns)) {
      if (pattern.test(summary)) {
        if (!results.has(name)) results.set(name, []);
        results.get(name)!.push(summary);
      }
    }
  }
  return results;
}

function formatSynthesisReportOriginal(result: SynthesisResult, date: string): string {
  let content = `# Learning Pattern Synthesis

**Period:** ${result.period}
**Generated:** ${date}
**Total Ratings:** ${result.totalRatings}
**Average Rating:** ${result.avgRating.toFixed(1)}/10

---

## Top Issues

${result.topIssues.length > 0
      ? result.topIssues.map((issue, i) => `${i + 1}. ${issue}`).join("\n")
      : "No significant issues detected"}

## Frustration Patterns

`;

  if (result.frustrations.length === 0) {
    content += "*No frustration patterns detected*\n\n";
  } else {
    for (const f of result.frustrations) {
      content += `### ${f.pattern}

- **Occurrences:** ${f.count}
- **Avg Rating:** ${f.avgRating.toFixed(1)}
- **Confidence:** ${(f.avgConfidence * 100).toFixed(0)}%
- **Examples:**
${f.examples.map((e) => `  - "${e}"`).join("\n")}

`;
    }
  }

  content += `## Success Patterns

`;

  if (result.successes.length === 0) {
    content += "*No success patterns detected*\n\n";
  } else {
    for (const s of result.successes) {
      content += `### ${s.pattern}

- **Occurrences:** ${s.count}
- **Avg Rating:** ${s.avgRating.toFixed(1)}
- **Examples:**
${s.examples.map((e) => `  - "${e}"`).join("\n")}

`;
    }
  }

  content += `## Recommendations

${result.recommendations.map((r, i) => `${i + 1}. ${r}`).join("\n")}

---

*Generated by LearningPatternSynthesis tool*
`;

  return content;
}

// ============================================================================
// Fixtures
// ============================================================================

const FIXED_NOW = new Date("2026-07-12T18:00:00.000Z");
const TZ = "UTC";

function rating(over: Partial<Rating>): Rating {
  return {
    timestamp: "2026-07-12T00:00:00.000Z",
    rating: 5,
    session_id: "s",
    source: "explicit",
    sentiment_summary: "",
    confidence: 0.9,
    ...over,
  };
}

const dirs: string[] = [];
function fixtureRoot(): string {
  const d = mkdtempSync(join(tmpdir(), "lps-"));
  dirs.push(d);
  return d;
}
afterEach(() => {
  while (dirs.length) rmSync(dirs.pop()!, { recursive: true, force: true });
});

function depsFor(root: string, over: Partial<Deps> = {}): Deps {
  const logged: string[] = [];
  const deps: Deps = {
    ratingsFile: join(root, "ratings.jsonl"),
    synthesisDir: join(root, "SYNTHESIS"),
    now: FIXED_NOW,
    tz: TZ,
    frustrationRules: FRUSTRATION_RULES,
    successRules: SUCCESS_RULES,
    log: (m) => logged.push(m),
    ...over,
  };
  (deps as Deps & { logged: string[] }).logged = logged;
  return deps;
}

// Representative summaries covering multi-bucket matches, misses, and both tables.
const SUMMARIES = [
  "the task was slow and took minutes to finish", // Time/Performance
  "incomplete work, missing pieces and a crash bug", // Incomplete + Tool/System Failures
  "wrong approach, total misunderstand", // Wrong Approach
  "over-engineered and too complex, unnecessary bloat", // Over-engineering + Tool? no
  "unclear, should have asked, confusing again repeat", // Communication + Repetitive
  "nothing notable here", // no match
  "quick and efficient, exactly perfect, clean and elegant", // Quick + Good Understanding + Clean
  "proactive and helpful above and beyond", // Proactive
];

// ============================================================================
// Byte-parity: scoreRules detection vs the original detectPatterns
// ============================================================================

describe("detectPatterns byte-parity (scoreRules vs original)", () => {
  test("frustration buckets: same keys, order, and members", () => {
    const got = detectPatterns(SUMMARIES, FRUSTRATION_RULES);
    const want = detectPatternsOriginal(SUMMARIES, FRUSTRATION_PATTERNS);
    expect([...got.keys()]).toEqual([...want.keys()]);
    for (const k of want.keys()) expect(got.get(k)).toEqual(want.get(k));
  });

  test("success buckets: same keys, order, and members", () => {
    const got = detectPatterns(SUMMARIES, SUCCESS_RULES);
    const want = detectPatternsOriginal(SUMMARIES, SUCCESS_PATTERNS);
    expect([...got.keys()]).toEqual([...want.keys()]);
    for (const k of want.keys()) expect(got.get(k)).toEqual(want.get(k));
  });

  test("top label + full bucket ranking match on a frustration-heavy corpus", () => {
    // Skew so one label dominates → assert the derived top-of-ranking is identical both ways.
    const corpus = [
      "slow slow took hours", // Time/Performance
      "delay, long wait", // Time/Performance
      "hang and wait", // Time/Performance
      "a crash bug", // Tool/System Failures
    ];
    const got = detectPatterns(corpus, FRUSTRATION_RULES);
    const want = detectPatternsOriginal(corpus, FRUSTRATION_PATTERNS);
    const rank = (m: Map<string, string[]>) =>
      [...m.entries()].sort((a, b) => b[1].length - a[1].length).map(([k, v]) => `${k}:${v.length}`);
    expect(rank(got)).toEqual(rank(want));
    expect(rank(got)[0]).toBe("Time/Performance Issues:3");
  });

  test("empty input → empty map", () => {
    expect([...detectPatterns([], FRUSTRATION_RULES).entries()]).toEqual([]);
  });
});

// ============================================================================
// Byte-parity: report rendering (lines() builder vs original template)
// ============================================================================

describe("formatSynthesisReport byte-parity (lines vs original template)", () => {
  const cases: Array<[string, SynthesisResult]> = [
    [
      "empty result",
      { period: "Weekly", totalRatings: 0, avgRating: 0, frustrations: [], successes: [], topIssues: [], recommendations: [] },
    ],
    [
      "populated result",
      analyzeRatings(
        [
          rating({ rating: 2, sentiment_summary: "slow and took minutes, a crash bug" }),
          rating({ rating: 3, sentiment_summary: "wrong approach, misunderstand" }),
          rating({ rating: 9, sentiment_summary: "quick and efficient, clean elegant" }),
          rating({ rating: 8, sentiment_summary: "understood exactly, perfect" }),
        ],
        "Monthly",
      ),
    ],
    [
      "frustrations only",
      analyzeRatings([rating({ rating: 1, sentiment_summary: "over-engineered, too complex bloat" })], "All Time"),
    ],
  ];

  for (const [name, result] of cases) {
    test(name, () => {
      const got = formatSynthesisReport(result, FIXED_NOW);
      const want = formatSynthesisReportOriginal(result, "2026-07-12");
      expect(got).toBe(want);
    });
  }
});

// ============================================================================
// loadRatings — malformed line skipping
// ============================================================================

describe("loadRatings", () => {
  test("parses NDJSON, skips blank + malformed lines", () => {
    const root = fixtureRoot();
    const file = join(root, "r.jsonl");
    writeFileSync(
      file,
      [JSON.stringify(rating({ rating: 4 })), "", "{ not json", JSON.stringify(rating({ rating: 8 }))].join("\n"),
    );
    const got = loadRatings(file);
    expect(got.length).toBe(2);
    expect(got.map((r) => r.rating)).toEqual([4, 8]);
  });

  test("absent file → empty array", () => {
    expect(loadRatings(join(fixtureRoot(), "missing.jsonl"))).toEqual([]);
  });
});

// ============================================================================
// analyzeRatings — thresholds + recommendations
// ============================================================================

describe("analyzeRatings", () => {
  test("splits frustrations (<=4) and successes (>=7); ratings 5-6 excluded from both", () => {
    const res = analyzeRatings(
      [
        rating({ rating: 4, sentiment_summary: "slow, minutes wasted" }),
        rating({ rating: 5, sentiment_summary: "quick and clean" }), // neither bucket
        rating({ rating: 6, sentiment_summary: "wrong approach" }), // neither bucket
        rating({ rating: 7, sentiment_summary: "quick efficient smooth" }),
      ],
      "Weekly",
    );
    expect(res.frustrations.map((f) => f.pattern)).toContain("Time/Performance Issues");
    expect(res.successes.map((s) => s.pattern)).toContain("Quick Resolution");
    // rating 6 "wrong approach" must NOT surface (only <=4 feed frustrations)
    expect(res.frustrations.map((f) => f.pattern)).not.toContain("Wrong Approach");
    expect(res.avgRating).toBeCloseTo((4 + 5 + 6 + 7) / 4, 10);
  });

  test("recommendation map fires per detected frustration label", () => {
    const res = analyzeRatings([rating({ rating: 2, sentiment_summary: "slow, took hours" })], "Weekly");
    expect(res.recommendations).toContain("Consider setting clearer time expectations and progress updates");
  });

  test("no frustrations → the fallback recommendation", () => {
    const res = analyzeRatings([rating({ rating: 9, sentiment_summary: "quick clean elegant" })], "Weekly");
    expect(res.recommendations).toEqual(["Continue current patterns - no major issues detected"]);
  });

  test("empty ratings → zeroed result", () => {
    const res = analyzeRatings([], "Weekly");
    expect(res).toEqual({
      period: "Weekly",
      totalRatings: 0,
      avgRating: 0,
      frustrations: [],
      successes: [],
      topIssues: [],
      recommendations: [],
    });
  });
});

// ============================================================================
// writeSynthesis — month-dir + filename shape, atomic write
// ============================================================================

describe("writeSynthesis", () => {
  test("writes YYYY-MM/<date>_<period>-patterns.md with the report body", () => {
    const root = fixtureRoot();
    const result = analyzeRatings([rating({ rating: 2, sentiment_summary: "slow minutes" })], "Weekly");
    const fp = writeSynthesis(result, "Weekly", join(root, "SYNTHESIS"), FIXED_NOW, TZ);
    expect(fp).toBe(join(root, "SYNTHESIS", "2026-07", "2026-07-12_weekly-patterns.md"));
    expect(existsSync(fp)).toBe(true);
    expect(readFileSync(fp, "utf-8")).toBe(formatSynthesisReport(result, FIXED_NOW));
  });

  test("multi-word period slugged in filename", () => {
    const root = fixtureRoot();
    const result = analyzeRatings([rating({ rating: 2, sentiment_summary: "slow" })], "All Time");
    const fp = writeSynthesis(result, "All Time", join(root, "SYNTHESIS"), FIXED_NOW, TZ);
    expect(fp.endsWith("2026-07-12_all-time-patterns.md")).toBe(true);
  });
});

// ============================================================================
// main — CLI integration (mkdtemp fixtures, fixed clock, injected deps)
// ============================================================================

function seedRatings(root: string, rows: Rating[]): void {
  mkdirSync(root, { recursive: true });
  writeFileSync(join(root, "ratings.jsonl"), rows.map((r) => JSON.stringify(r)).join("\n") + "\n");
}

describe("main", () => {
  test("--help prints usage and returns 0 without reading ratings", () => {
    const root = fixtureRoot();
    const deps = depsFor(root);
    expect(main(["--help"], deps)).toBe(0);
    const logged = (deps as Deps & { logged: string[] }).logged;
    expect(logged.join("\n")).toContain("Aggregate ratings into actionable patterns");
  });

  test("missing ratings file → 0 and 'No ratings file found'", () => {
    const root = fixtureRoot();
    const deps = depsFor(root);
    expect(main(["--week"], deps)).toBe(0);
    const logged = (deps as Deps & { logged: string[] }).logged;
    expect(logged.some((l) => l.startsWith("No ratings file found at:"))).toBe(true);
  });

  test("--week default: filters last 7 days and writes a weekly report", () => {
    const root = fixtureRoot();
    seedRatings(root, [
      rating({ rating: 2, timestamp: "2026-07-11T00:00:00Z", sentiment_summary: "slow minutes" }), // in window
      rating({ rating: 3, timestamp: "2026-06-01T00:00:00Z", sentiment_summary: "wrong approach" }), // out (>7d)
    ]);
    const deps = depsFor(root);
    expect(main([], deps)).toBe(0); // no flag == week
    const out = join(root, "SYNTHESIS", "2026-07", "2026-07-12_weekly-patterns.md");
    expect(existsSync(out)).toBe(true);
    const body = readFileSync(out, "utf-8");
    expect(body).toContain("**Period:** Weekly");
    expect(body).toContain("Time/Performance Issues"); // from the in-window rating
    expect(body).not.toContain("Wrong Approach"); // filtered out by window
  });

  test("--month widens the window", () => {
    const root = fixtureRoot();
    seedRatings(root, [
      rating({ rating: 3, timestamp: "2026-06-20T00:00:00Z", sentiment_summary: "wrong approach mistake" }), // ~22d
    ]);
    const deps = depsFor(root);
    expect(main(["--month"], deps)).toBe(0);
    const out = join(root, "SYNTHESIS", "2026-07", "2026-07-12_monthly-patterns.md");
    expect(existsSync(out)).toBe(true);
    expect(readFileSync(out, "utf-8")).toContain("Wrong Approach");
  });

  test("--all includes everything valid; invalid timestamps dropped", () => {
    const root = fixtureRoot();
    seedRatings(root, [
      rating({ rating: 2, timestamp: "2020-01-01T00:00:00Z", sentiment_summary: "slow" }),
      rating({ rating: 2, timestamp: "not-a-date", sentiment_summary: "crash bug" }),
    ]);
    const deps = depsFor(root);
    expect(main(["--all"], deps)).toBe(0);
    const out = join(root, "SYNTHESIS", "2026-07", "2026-07-12_all-time-patterns.md");
    const body = readFileSync(out, "utf-8");
    expect(body).toContain("Time/Performance Issues"); // the valid old one
    expect(body).not.toContain("Tool/System Failures"); // invalid-timestamp rating dropped
  });

  test("--dry-run does not write a file but still returns 0", () => {
    const root = fixtureRoot();
    seedRatings(root, [rating({ rating: 2, timestamp: "2026-07-11T00:00:00Z", sentiment_summary: "slow minutes" })]);
    const deps = depsFor(root);
    expect(main(["--week", "--dry-run"], deps)).toBe(0);
    expect(existsSync(join(root, "SYNTHESIS"))).toBe(false);
    const logged = (deps as Deps & { logged: string[] }).logged;
    expect(logged.some((l) => l.includes("DRY RUN"))).toBe(true);
  });

  test("empty window → 0 and 'No ratings in this period', no file", () => {
    const root = fixtureRoot();
    seedRatings(root, [rating({ rating: 2, timestamp: "2020-01-01T00:00:00Z", sentiment_summary: "slow" })]);
    const deps = depsFor(root);
    expect(main(["--week"], deps)).toBe(0);
    expect(existsSync(join(root, "SYNTHESIS"))).toBe(false);
    const logged = (deps as Deps & { logged: string[] }).logged;
    expect(logged.some((l) => l.includes("No ratings in this period"))).toBe(true);
  });
});

// ============================================================================
// RT-2 framework-dir resolution (AD-9.3)
// ============================================================================

describe("RT-2 framework-dir resolution (AD-9.3)", () => {
  // `defaultDeps()` is NOT exported, so drive the resolution through main() with its default deps and
  // observe the resolved ratingsFile via the "No ratings file found at: <path>" log (frameworkDir has no
  // file on a fresh/absolute path → main returns early). synthesisDir shares the same frameworkDir base,
  // so proving ratingsFile proves the resolution.
  const KEYS = ["LIFEOS_DIR", "PAI_DIR", "HOME"] as const;
  let saved: Record<string, string | undefined>;
  beforeEach(() => {
    saved = Object.fromEntries(KEYS.map((k) => [k, process.env[k]]));
  });
  afterEach(() => {
    for (const k of KEYS) {
      if (saved[k] === undefined) delete process.env[k];
      else process.env[k] = saved[k];
    }
  });

  function ratingsPathFromMain(): string {
    const logs: string[] = [];
    const orig = console.log;
    console.log = (...a: unknown[]) => {
      logs.push(a.map((x) => String(x)).join(" "));
    };
    try {
      main(["--week"]); // no deps → defaultDeps() computes the framework-dir-derived paths
    } finally {
      console.log = orig;
    }
    const line = logs.find((l) => l.startsWith("No ratings file found at:"));
    if (!line) throw new Error(`no ratings-file log captured: ${logs.join(" | ")}`);
    return line.replace("No ratings file found at: ", "");
  }

  test("LIFEOS_DIR wins over PAI_DIR", () => {
    process.env.LIFEOS_DIR = "/life";
    process.env.PAI_DIR = "/pai";
    expect(ratingsPathFromMain()).toBe(join("/life", "MEMORY", "LEARNING", "SIGNALS", "ratings.jsonl"));
  });

  test("PAI_DIR honored when LIFEOS_DIR unset", () => {
    delete process.env.LIFEOS_DIR;
    process.env.PAI_DIR = "/pai";
    expect(ratingsPathFromMain()).toBe(join("/pai", "MEMORY", "LEARNING", "SIGNALS", "ratings.jsonl"));
  });

  test("neither env set → resolver falls back to LIFEOS under a fresh temp home", () => {
    delete process.env.LIFEOS_DIR;
    delete process.env.PAI_DIR;
    const home = mkdtempSync(join(tmpdir(), "rt2-"));
    process.env.HOME = home;
    try {
      expect(ratingsPathFromMain()).toBe(
        join(home, ".claude", "LIFEOS", "MEMORY", "LEARNING", "SIGNALS", "ratings.jsonl"),
      );
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });

  test("legacy PAI tree present → resolver picks PAI", () => {
    delete process.env.LIFEOS_DIR;
    delete process.env.PAI_DIR;
    const home = mkdtempSync(join(tmpdir(), "rt2-"));
    mkdirSync(join(home, ".claude", "PAI"), { recursive: true });
    process.env.HOME = home;
    try {
      expect(ratingsPathFromMain()).toBe(
        join(home, ".claude", "PAI", "MEMORY", "LEARNING", "SIGNALS", "ratings.jsonl"),
      );
    } finally {
      rmSync(home, { recursive: true, force: true });
    }
  });
});
