import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import {
  assessHealth,
  computeSimilarity,
  findCrossPrinciples,
  generateHealthReport,
  generatePrinciplesReport,
  main,
  parseFrame,
  type CrossPrinciple,
  type FrameData,
  type FrameHealth,
} from "./wisdom-cross-frame-synthesizer";

// ── Byte-parity references: the ORIGINAL template literals, verbatim, parameterized on the date ──
// (the origin computed date = new Date().toISOString().split('T')[0]; here we inject it so the proof's
//  isoDate(now) and this reference see the same stamp). If the lines()-rewrite drifts a single byte,
//  these assertions fail.

function refPrinciplesReport(
  crossPrinciples: CrossPrinciple[],
  frames: FrameData[],
  date: string,
): string {
  return `# Verified Cross-Domain Principles

**Generated:** ${date}
**Frames Analyzed:** ${frames.length}
**Cross-Domain Principles Found:** ${crossPrinciples.length}

---

## Principles Confirmed Across Multiple Domains

${
    crossPrinciples.length === 0
      ? "*No cross-domain principles found yet. Frames need more observations.*"
      : crossPrinciples
          .map(
            (cp, i) => `### ${i + 1}. ${cp.principle}

- **Domains:** ${cp.domains.join(", ")}
- **Confidence:** ${cp.confidence}%
- **Evidence:** ${cp.evidence}
`,
          )
          .join("\n")
  }

---

## Frame Coverage

| Domain | Confidence | Observations | Principles | Anti-Patterns |
|--------|-----------|-------------|------------|---------------|
${frames
    .map(
      (f) =>
        `| ${f.domain} | ${f.confidence}% | ${f.observationCount}+ | ${f.principles.length} | ${f.antiPatterns.length} |`,
    )
    .join("\n")}

---

*Generated by WisdomCrossFrameSynthesizer*
`;
}

function refHealthReport(healthData: FrameHealth[], date: string): string {
  return `# Wisdom Frame Health Report

**Generated:** ${date}
**Total Frames:** ${healthData.length}

## Frame Status

| Domain | Health | Confidence | Observations | Last Updated | Principles | Anti-Patterns |
|--------|--------|-----------|-------------|-------------|------------|---------------|
${healthData
    .map((h) => {
      const icon = h.health === "growing" ? "🟢" : h.health === "stable" ? "🟡" : "🔴";
      return `| ${h.domain} | ${icon} ${h.health} | ${h.confidence}% | ${h.observationCount}+ | ${h.lastCrystallized} | ${h.principleCount} | ${h.antiPatternCount} |`;
    })
    .join("\n")}

## Recommendations

${healthData
    .filter((h) => h.health === "stale")
    .map((h) => `- **${h.domain}:** Stale — needs new observations or review`)
    .join("\n") || "- All frames are active"}
${healthData
    .filter((h) => h.principleCount === 0)
    .map((h) => `- **${h.domain}:** No crystallized principles yet — needs more observations`)
    .join("\n") || ""}
${healthData
    .filter((h) => h.antiPatternCount === 0)
    .map((h) => `- **${h.domain}:** No anti-patterns captured — review recent failures`)
    .join("\n") || ""}

---

*Generated by WisdomCrossFrameSynthesizer*
`;
}

// ── Fixtures ──

function frameMd(opts: {
  confidence?: string;
  obs?: string;
  cryst?: string;
  principles?: string[];
  antiPatterns?: string[];
  crossConnections?: string[];
}): string {
  const {
    confidence = "85%",
    obs = "42",
    cryst = "2026-07-01",
    principles = [],
    antiPatterns = [],
    crossConnections = [],
  } = opts;
  let md = `# Frame\n\n**Confidence:** ${confidence}\n**Observation Count:** ${obs}\n**Last Crystallized:** ${cryst}\n\n## Core Principles\n\n`;
  for (const p of principles) md += `### ${p} [CRYSTAL]\n\nsome body text\n\n`;
  md += `## Anti-Patterns\n\n`;
  for (const ap of antiPatterns) md += `### ${ap}\n\ndetail\n\n`;
  md += `## Cross-Frame Connections\n\n`;
  for (const cc of crossConnections) md += `- **${cc}** relates here\n`;
  md += `\n## Notes\n\ntrailing section that must not leak into anti/cross parsing\n`;
  return md;
}

let dir: string;
beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), "wcfs-"));
});
afterEach(() => {
  rmSync(dir, { recursive: true, force: true });
});

const NOW = new Date("2026-07-12T10:00:00Z");
const NOW_ISO = "2026-07-12";

// ── computeSimilarity ──

describe("computeSimilarity", () => {
  test("identical significant-word titles → 1", () => {
    expect(computeSimilarity("Retrieval beats recall", "Retrieval beats recall")).toBe(1);
  });

  test("Jaccard = |∩| / |∪| over stopword-filtered, len>2 tokens", () => {
    // A: {retrieval, beats, recall}  B: {retrieval, beats, memory}
    // ∩ = {retrieval, beats} = 2 ; ∪ = {retrieval, beats, recall, memory} = 4  → 0.5
    expect(computeSimilarity("Retrieval beats recall", "Retrieval beats memory")).toBe(0.5);
  });

  test("stopwords and short (<=2 char) tokens are dropped before scoring", () => {
    // "the of a to" are all stopwords/short → empty set → 0
    expect(computeSimilarity("the of a to", "systems win")).toBe(0);
  });

  test("disjoint significant words → 0", () => {
    expect(computeSimilarity("systems discipline", "context compounds")).toBe(0);
  });

  test("empty input → 0 (either side empty)", () => {
    expect(computeSimilarity("", "anything here")).toBe(0);
    expect(computeSimilarity("something", "")).toBe(0);
  });

  test("case-insensitive", () => {
    expect(computeSimilarity("SYSTEMS BEAT DISCIPLINE", "systems beat discipline")).toBe(1);
  });
});

// ── parseFrame ──

describe("parseFrame", () => {
  test("parses meta, principles, anti-patterns, cross-connections", () => {
    const p = join(dir, "cognition.md");
    writeFileSync(
      p,
      frameMd({
        confidence: "85%",
        obs: "42",
        cryst: "2026-07-01",
        principles: ["Retrieval beats recall", "Systems beat discipline"],
        antiPatterns: ["Trusting parametric memory", "Skipping verification"],
        crossConnections: ["business.md", "health.md"],
      }),
    );
    const f = parseFrame(p);
    expect(f.domain).toBe("cognition");
    expect(f.path).toBe(p);
    expect(f.confidence).toBe(85);
    expect(f.observationCount).toBe(42);
    expect(f.lastCrystallized).toBe("2026-07-01");
    expect(f.principles).toEqual(["Retrieval beats recall", "Systems beat discipline"]);
    expect(f.antiPatterns).toEqual(["Trusting parametric memory", "Skipping verification"]);
    expect(f.crossConnections).toEqual(["business.md", "health.md"]);
  });

  test("missing meta → origin defaults (50 / 0 / 'unknown')", () => {
    const p = join(dir, "bare.md");
    writeFileSync(p, `# Frame\n\n## Core Principles\n\nnothing crystallized\n`);
    const f = parseFrame(p);
    expect(f.confidence).toBe(50);
    expect(f.observationCount).toBe(0);
    expect(f.lastCrystallized).toBe("unknown");
    expect(f.principles).toEqual([]);
    expect(f.antiPatterns).toEqual([]);
    expect(f.crossConnections).toEqual([]);
  });

  test("obs count with a suffix keeps the leading integer only (origin \\d+)", () => {
    const p = join(dir, "suffix.md");
    writeFileSync(p, frameMd({ obs: "17 observations (last 30d)" }));
    expect(parseFrame(p).observationCount).toBe(17);
  });

  test("last crystallized keeps the first whitespace token only (origin \\S+)", () => {
    const p = join(dir, "cryst.md");
    writeFileSync(p, frameMd({ cryst: "2026-06-30 12:34:56" }));
    expect(parseFrame(p).lastCrystallized).toBe("2026-06-30");
  });

  test("a nested ### inside Anti-Patterns is captured; the trailing ## Notes section does not leak", () => {
    const p = join(dir, "boundary.md");
    writeFileSync(p, frameMd({ antiPatterns: ["Only anti here"] }));
    const f = parseFrame(p);
    expect(f.antiPatterns).toEqual(["Only anti here"]);
  });
});

// ── findCrossPrinciples ──

function frame(overrides: Partial<FrameData>): FrameData {
  return {
    domain: "d",
    path: "/x",
    confidence: 50,
    observationCount: 0,
    lastCrystallized: "unknown",
    principles: [],
    antiPatterns: [],
    crossConnections: [],
    ...overrides,
  };
}

describe("findCrossPrinciples", () => {
  test("similar principles across 2 frames pair up, sorted by descending confidence", () => {
    const frames = [
      frame({ domain: "cognition", confidence: 90, principles: ["Retrieval beats recall"] }),
      frame({ domain: "business", confidence: 70, principles: ["Retrieval beats memory"] }),
    ];
    const cps = findCrossPrinciples(frames);
    expect(cps.length).toBe(1);
    expect(cps[0].principle).toBe("Retrieval beats recall / Retrieval beats memory");
    expect(cps[0].domains).toEqual(["cognition", "business"]);
    expect(cps[0].confidence).toBe(70); // min of the two
  });

  test("dissimilar principles do not pair (0.3 cutoff)", () => {
    const frames = [
      frame({ domain: "a", principles: ["Systems beat discipline"] }),
      frame({ domain: "b", principles: ["Context quality compounds"] }),
    ];
    expect(findCrossPrinciples(frames)).toEqual([]);
  });

  test("explicit cross-connections add a pairing when none exists", () => {
    const frames = [
      frame({ domain: "cognition", confidence: 80, crossConnections: ["business.md"] }),
      frame({ domain: "business", confidence: 60 }),
    ];
    const cps = findCrossPrinciples(frames);
    expect(cps.length).toBe(1);
    expect(cps[0].principle).toBe("Explicit connection: cognition ↔ business");
    expect(cps[0].domains).toEqual(["cognition", "business"]);
  });

  test("explicit connection is skipped when the pair already exists from similarity", () => {
    const frames = [
      frame({
        domain: "cognition",
        confidence: 90,
        principles: ["Retrieval beats recall"],
        crossConnections: ["business.md"],
      }),
      frame({ domain: "business", confidence: 70, principles: ["Retrieval beats recall"] }),
    ];
    const cps = findCrossPrinciples(frames);
    // one similarity pairing; the explicit connection finds the existing pair and adds nothing
    expect(cps.length).toBe(1);
    expect(cps[0].principle).toBe("Retrieval beats recall / Retrieval beats recall");
  });
});

// ── assessHealth ──

describe("assessHealth", () => {
  test("recent + many observations → growing", () => {
    const h = assessHealth(
      frame({ domain: "d", lastCrystallized: "2026-07-08", observationCount: 20 }),
      NOW,
    );
    expect(h.health).toBe("growing");
  });

  test("within 30 days (or recent but few obs) → stable", () => {
    expect(
      assessHealth(frame({ lastCrystallized: "2026-06-20", observationCount: 5 }), NOW).health,
    ).toBe("stable");
    // recent but too few observations falls through to the <=30d branch
    expect(
      assessHealth(frame({ lastCrystallized: "2026-07-10", observationCount: 3 }), NOW).health,
    ).toBe("stable");
  });

  test("older than 30 days → stale", () => {
    expect(
      assessHealth(frame({ lastCrystallized: "2026-05-01", observationCount: 99 }), NOW).health,
    ).toBe("stale");
  });

  test("unknown crystallized date → 999 days → stale", () => {
    expect(assessHealth(frame({ lastCrystallized: "unknown" }), NOW).health).toBe("stale");
  });

  test("carries through the count fields", () => {
    const h = assessHealth(
      frame({
        domain: "d",
        confidence: 77,
        observationCount: 12,
        lastCrystallized: "2026-07-09",
        principles: ["a", "b"],
        antiPatterns: ["x"],
        crossConnections: ["y", "z", "w"],
      }),
      NOW,
    );
    expect(h).toEqual({
      domain: "d",
      confidence: 77,
      observationCount: 12,
      lastCrystallized: "2026-07-09",
      principleCount: 2,
      antiPatternCount: 1,
      crossConnectionCount: 3,
      health: "growing",
    });
  });
});

// ── Report byte-parity ──

describe("generatePrinciplesReport — byte-parity vs origin template", () => {
  const frames = [
    frame({ domain: "cognition", confidence: 90, observationCount: 42, principles: ["a", "b"], antiPatterns: ["x"] }),
    frame({ domain: "business", confidence: 70, observationCount: 8, principles: ["c"], antiPatterns: [] }),
  ];

  test("with cross-principles", () => {
    const cps: CrossPrinciple[] = [
      { principle: "P1 / P2", domains: ["cognition", "business"], confidence: 70, evidence: "Shared principle across cognition and business" },
      { principle: "Explicit connection: cognition ↔ health", domains: ["cognition", "health"], confidence: 90, evidence: "Declared in cognition frame cross-connections" },
    ];
    expect(generatePrinciplesReport(cps, frames, NOW)).toBe(refPrinciplesReport(cps, frames, NOW_ISO));
  });

  test("empty cross-principles branch", () => {
    expect(generatePrinciplesReport([], frames, NOW)).toBe(refPrinciplesReport([], frames, NOW_ISO));
  });

  test("no frames at all", () => {
    expect(generatePrinciplesReport([], [], NOW)).toBe(refPrinciplesReport([], [], NOW_ISO));
  });
});

describe("generateHealthReport — byte-parity vs origin template", () => {
  const healthData: FrameHealth[] = [
    { domain: "cognition", confidence: 90, observationCount: 42, lastCrystallized: "2026-07-09", principleCount: 2, antiPatternCount: 1, crossConnectionCount: 0, health: "growing" },
    { domain: "business", confidence: 60, observationCount: 3, lastCrystallized: "2026-05-01", principleCount: 0, antiPatternCount: 0, crossConnectionCount: 1, health: "stale" },
  ];

  test("mixed health with stale + zero-principle + zero-anti recommendations", () => {
    expect(generateHealthReport(healthData, NOW)).toBe(refHealthReport(healthData, NOW_ISO));
  });

  test("all-active branch (no stale) → '- All frames are active'", () => {
    const allGood: FrameHealth[] = [
      { domain: "cognition", confidence: 90, observationCount: 42, lastCrystallized: "2026-07-09", principleCount: 2, antiPatternCount: 1, crossConnectionCount: 0, health: "growing" },
    ];
    expect(generateHealthReport(allGood, NOW)).toBe(refHealthReport(allGood, NOW_ISO));
  });

  test("empty health data", () => {
    expect(generateHealthReport([], NOW)).toBe(refHealthReport([], NOW_ISO));
  });
});

// ── main() end-to-end (hermetic via PAI_DIR) ──

function seedFrames(paiDir: string) {
  const framesDir = join(paiDir, "MEMORY", "WISDOM", "FRAMES");
  mkdirSync(framesDir, { recursive: true });
  writeFileSync(
    join(framesDir, "cognition.md"),
    frameMd({
      confidence: "90%",
      obs: "42",
      cryst: "2026-07-09",
      principles: ["Retrieval beats recall"],
      antiPatterns: ["Trusting parametric memory"],
    }),
  );
  writeFileSync(
    join(framesDir, "business.md"),
    frameMd({
      confidence: "70%",
      obs: "8",
      cryst: "2026-07-08",
      principles: ["Retrieval beats memory"],
    }),
  );
}

describe("main()", () => {
  const savedPaiDir = process.env.PAI_DIR;
  afterEach(() => {
    if (savedPaiDir === undefined) delete process.env.PAI_DIR;
    else process.env.PAI_DIR = savedPaiDir;
  });

  test("--help returns 0 and writes nothing", () => {
    process.env.PAI_DIR = dir;
    expect(main(["--help"])).toBe(0);
    expect(existsSync(join(dir, "MEMORY"))).toBe(false);
  });

  test("-h short flag returns 0", () => {
    process.env.PAI_DIR = dir;
    expect(main(["-h"])).toBe(0);
  });

  test("no frames directory → 0, no write", () => {
    process.env.PAI_DIR = dir;
    expect(main([])).toBe(0);
    expect(existsSync(join(dir, "MEMORY", "WISDOM", "PRINCIPLES"))).toBe(false);
  });

  test("empty frames directory → 0, no write", () => {
    process.env.PAI_DIR = dir;
    mkdirSync(join(dir, "MEMORY", "WISDOM", "FRAMES"), { recursive: true });
    expect(main([])).toBe(0);
    expect(existsSync(join(dir, "MEMORY", "WISDOM", "PRINCIPLES", "verified.md"))).toBe(false);
  });

  test("synthesis run writes verified.md AND frame-health.md", () => {
    process.env.PAI_DIR = dir;
    seedFrames(dir);
    expect(main([])).toBe(0);
    const verified = join(dir, "MEMORY", "WISDOM", "PRINCIPLES", "verified.md");
    const health = join(dir, "MEMORY", "WISDOM", "META", "frame-health.md");
    expect(existsSync(verified)).toBe(true);
    expect(existsSync(health)).toBe(true);
    const v = readFileSync(verified, "utf-8");
    expect(v).toContain("# Verified Cross-Domain Principles");
    expect(v).toContain("| cognition | 90% | 42+ | 1 | 1 |");
    expect(v).toContain("| business | 70% | 8+ | 1 | 0 |");
    // the two similar principles pair up. The join order is `${frameA} / ${frameB}` in frame-discovery
    // (readdirSync/walkFiles) order — FS-dependent in BOTH the original and this port, and verified.md
    // has no downstream parser — so assert the pairing regardless of which side lands first.
    expect(v).toMatch(
      /Retrieval beats (recall|memory) \/ Retrieval beats (recall|memory)/,
    );
    expect(readFileSync(health, "utf-8")).toContain("# Wisdom Frame Health Report");
  });

  test("--dry-run writes nothing", () => {
    process.env.PAI_DIR = dir;
    seedFrames(dir);
    expect(main(["--dry-run"])).toBe(0);
    expect(existsSync(join(dir, "MEMORY", "WISDOM", "PRINCIPLES", "verified.md"))).toBe(false);
    expect(existsSync(join(dir, "MEMORY", "WISDOM", "META", "frame-health.md"))).toBe(false);
  });

  test("--health writes only frame-health.md", () => {
    process.env.PAI_DIR = dir;
    seedFrames(dir);
    expect(main(["--health"])).toBe(0);
    expect(existsSync(join(dir, "MEMORY", "WISDOM", "META", "frame-health.md"))).toBe(true);
    expect(existsSync(join(dir, "MEMORY", "WISDOM", "PRINCIPLES", "verified.md"))).toBe(false);
  });

  test("--health --dry-run writes nothing", () => {
    process.env.PAI_DIR = dir;
    seedFrames(dir);
    expect(main(["--health", "--dry-run"])).toBe(0);
    expect(existsSync(join(dir, "MEMORY", "WISDOM", "META", "frame-health.md"))).toBe(false);
  });
});
