// cn-deploy — bundle the `src/cn/` Obsidian edge into a vault as a single generated artifact.
//
//   std cn deploy --vault <dir>   ->   <vault>/Scripts/cn.js
//
// THIN SPEC + WIRING over the promoted engine (Story 8.3 D-1). Everything that is edge-agnostic — the watch
// loop, the ignore-list, the debounce, the build, the guards, the TOCTOU re-check, skip-if-identical, the
// 0/1/2 contract — now lives in `./edge-deploy` and is shared with `dashkit-deploy.ts`. This file supplies
// only cn's `EdgeSpec` (banner, artifact name, entrypoint, watched dirs, plugin preflight) and re-exposes
// the cn-bound surface the tests and `main.ts` already import.
//
// ONE-WAY (AD-5, GIT-SoT). `src/cn/` is the source of truth; the vault holds build output only and is
// never a second source. The artifact carries a generated-file banner, and deploy REFUSES to clobber a
// target that lacks cn's banner prefix — that means someone hand-authored the file (or it is another edge's
// artifact) and their work would be lost.
//
// IDENTITY-FREE (D4/NFR3). No vault path, vault name, or vault literal appears here or anywhere in
// `src/**`. The path arrives only as `--vault`; Pedro's actual path lives caller-side.

import { join } from "node:path";

import { CN_PLUGIN_CONTRACT } from "../cn/plugins";
import { verifyPlugins } from "../core/plugin-contract";
import { CnVerifyError, readVaultPlugins, renderFindings } from "./cn-verify";
import {
  type DeployResult,
  type EdgeDeployDeps,
  type EdgeSpec,
  EdgeDeployError,
  type WatchHandle,
  WATCH_DEBOUNCE_MS,
  artifactPath as edgeArtifactPath,
  buildBundle as edgeBuildBundle,
  deployOnce as edgeDeployOnce,
  isBundleRelevant,
  makeWatchAdapter,
  resolveTarget as edgeResolveTarget,
  runEdgeDeploy,
  runWatch,
} from "./edge-deploy";

/** Marker every generated artifact starts with — the clobber guard keys on this exact prefix. */
export const BANNER_PREFIX = "// GENERATED by `std cn deploy`";

/** Line 1 of every artifact. Emitted via Bun.build's `banner`, so it is inside the build's determinism. */
export const BANNER =
  `${BANNER_PREFIX} from std/src/cn — do not edit. Edit std/src/cn and redeploy.`;

/**
 * cn's error type, kept as an alias of the promoted `EdgeDeployError` so `toThrow(CnDeployError)` and every
 * `instanceof` in the tests keep matching the class the engine actually throws (they are the SAME class).
 */
export { EdgeDeployError as CnDeployError };

// Re-export the generic engine surface the cn tests and main.ts already import from `./cn-deploy`, so the
// promotion is import-path-transparent to them (D-1: the test diff is import paths + spec-threading only).
export { WATCH_DEBOUNCE_MS, isBundleRelevant, makeWatchAdapter, runWatch };
export type { DeployResult, WatchHandle };
/** The deps shape main.ts threads through for the `cn deploy --watch` callsite. */
export type CnDeployDeps = EdgeDeployDeps;

/**
 * Run cn's plugin-envelope contract against the target vault BEFORE building (7.3 AC4) — declared ≠ decorative.
 *
 * An `error` finding means a required foundation is missing, disabled, or registered-but-not-installed.
 * Deploying a bundle that CodeScript Toolkit cannot load, or that calls a Dataview which is not there, is
 * a guaranteed broken note — so this throws and the caller aborts with exit 1 having written NOTHING
 * (fail-loud, FR5). `warn`/`info` findings are returned as lines for the caller to print; drift never
 * blocks a deploy (AD-6: no hard version-pins).
 *
 * IMPORT EDGE: this reaches `src/cn/plugins.ts` — pure data + comparator, no DOM — via `cn-verify`'s
 * reader. It never imports `src/cn/index.ts`, which would drag DOM types into the Bun typecheck graph.
 *
 * ONCE PER INVOCATION, never per rebuild: the engine calls `spec.preflight` ahead of the first build, so
 * `--watch` preflights at startup only. The plugin set does not change on a source save, and re-reading
 * the vault on every keystroke would hammer iCloud.
 */
export function preflightVault(vault: string): string[] {
  let findings;
  try {
    findings = verifyPlugins(readVaultPlugins(vault), CN_PLUGIN_CONTRACT, "cn");
  } catch (e) {
    // Re-badge so the caller's single `EdgeDeployError` catch keeps the 0/1/2 contract. The guards are
    // the same guards `resolveTarget` already ran, plus this command's own community-plugins.json ones.
    throw e instanceof CnVerifyError ? new EdgeDeployError(e.message) : e;
  }
  const errors = findings.filter((f) => f.severity === "error");
  if (errors.length > 0) {
    throw new EdgeDeployError(
      `plugin envelope check failed — refusing to deploy into ${vault}\n` +
        renderFindings(errors)
          .map((l) => (l === "" ? l : `  ${l}`)) // never indent the blank separator into whitespace
          .join("\n"),
    );
  }
  return renderFindings(findings.filter((f) => f.severity !== "ok"));
}

/** The `src/cn/index.ts` entrypoint, resolved relative to THIS file — never a hardcoded absolute path. */
export function entrypoint(): string {
  return join(import.meta.dir, "..", "cn", "index.ts");
}

/** The directories the bundle MAY contain (AD-5 rule 2), resolved relative to THIS file — never absolute. */
export function watchDirs(): string[] {
  return [join(import.meta.dir, "..", "cn"), join(import.meta.dir, "..", "core")];
}

/**
 * cn's `EdgeSpec`: the only thing the promoted engine needs to build/watch/deploy the cn edge. The banner
 * prefix is cn-SPECIFIC (never a shared literal) so a dashkit artifact cannot satisfy cn's clobber guard.
 */
export const CN_SPEC: EdgeSpec = {
  name: "cn",
  artifact: "cn.js",
  entrypoint: entrypoint(),
  watchDirs: watchDirs(),
  bannerPrefix: BANNER_PREFIX,
  banner: BANNER,
  usage:
    "usage: std cn deploy --vault <dir> [--watch]   # bundle src/cn -> <vault>/Scripts/cn.js\n" +
    "       std cn verify --vault <dir>             # check the vault against cn's plugin envelope",
  formats: ["esm", "cjs"],
  preflight: preflightVault,
};

/** Where the bundle lands inside a vault. Pure — no fs touched. */
export function artifactPath(vault: string): string {
  return edgeArtifactPath(CN_SPEC, vault);
}

/**
 * Validate that `vault` is a usable Obsidian vault and that the target is safe to overwrite, then return
 * the artifact path (see the engine's `resolveTarget` for the full fail-loud contract).
 */
export function resolveTarget(vault: string | undefined): string {
  return edgeResolveTarget(CN_SPEC, vault);
}

/** Bundle `src/cn/index.ts` into a single string with cn's banner as line 1 (see the engine's buildBundle). */
export function buildBundle(
  format: "esm" | "cjs" = "esm",
  entry: string = entrypoint(),
): Promise<string> {
  return edgeBuildBundle(CN_SPEC, format, entry);
}

/** One full deploy cycle for cn (see the engine's deployOnce for the skip-if-identical / read-back contract). */
export function deployOnce(
  vault: string,
  format: "esm" | "cjs",
  entry: string = entrypoint(),
): Promise<DeployResult> {
  return edgeDeployOnce(CN_SPEC, vault, format, entry);
}

/**
 * `std cn deploy --vault <dir> [--watch]` — validate, build in memory, write atomically, read back.
 * With `--watch`, the same deploy then stays resident and re-runs on every save under `src/cn` + `src/core`.
 * Returns a process exit code: 0 ok, 1 fail-loud, 2 usage. A thin delegate to the promoted engine (D-1).
 */
export function runCnDeploy(argv: string[], deps: CnDeployDeps = {}): Promise<number> {
  return runEdgeDeploy(CN_SPEC, argv, deps);
}
