// cn-deploy — bundle the `src/cn/` Obsidian edge into a vault as a single generated artifact.
//
//   std cn deploy --vault <dir>   ->   <vault>/Scripts/cn.js
//
// ONE-WAY (AD-5, GIT-SoT). `src/cn/` is the source of truth; the vault holds build output only and is
// never a second source. The artifact carries a generated-file banner, and deploy REFUSES to clobber a
// target that lacks it — that means someone hand-authored the file and their work would be lost.
//
// BUN EDGE, deliberately NOT inside src/cn/. `src/cn/` is a DOM-only slice; putting fs/build code in it
// would drag node/fs into the graph the bundler walks. This file never `import`s from `src/cn/` either —
// it references the entrypoint BY PATH, so no import edge forms (that would put DOM types in the Bun
// typecheck graph and could make a cycle Gate 5 flags).
//
// NO REPO-SIDE BUILD OUTPUT (D5/NFR6). The in-process `Bun.build()` API returns the artifact in memory
// and we write the text ourselves. Never `--outdir`, never a `dist/` — the only file produced is the one
// inside the caller's vault.
//
// IDENTITY-FREE (D4/NFR3). No vault path, vault name, or vault literal appears here or anywhere in
// `src/**`. The path arrives only as `--vault`; Pedro's actual path lives caller-side.

import { join } from "node:path";

import { flagValue } from "../core/args";
import { atomicWrite, exists, readIfExists } from "../fsx/index";

/** Marker every generated artifact starts with — the clobber guard keys on this exact prefix. */
export const BANNER_PREFIX = "// GENERATED by `std cn deploy`";

/** Line 1 of every artifact. Emitted via Bun.build's `banner`, so it is inside the build's determinism. */
export const BANNER =
  `${BANNER_PREFIX} from std/src/cn — do not edit. Edit std/src/cn and redeploy.`;

/** Thrown for every fail-loud condition (AC6). The CLI prints `.message` and exits 1. */
export class CnDeployError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "CnDeployError";
  }
}

/** Where the bundle lands inside a vault. Pure — no fs touched. */
export function artifactPath(vault: string): string {
  return join(vault, "Scripts", "cn.js");
}

/** The `src/cn/index.ts` entrypoint, resolved relative to THIS file — never a hardcoded absolute path. */
export function entrypoint(): string {
  return join(import.meta.dir, "..", "cn", "index.ts");
}

/**
 * Validate that `vault` is a usable Obsidian vault and that the target is safe to overwrite, then return
 * the artifact path. Effectful only in that it STATS — it writes nothing, so the guards unit-test against
 * a temp dir without a build.
 *
 * Fails loud (AC6) when: `vault` is missing/empty; `<vault>` does not exist; `<vault>/.obsidian` does not
 * exist (not an Obsidian vault); or the target file exists WITHOUT the banner (hand-authored — refuse to
 * clobber and tell the user to move it aside).
 */
export function resolveTarget(vault: string | undefined): string {
  if (vault === undefined || vault === "") {
    throw new CnDeployError("--vault <dir> is required (the Obsidian vault to deploy into)");
  }
  if (!exists(vault)) {
    throw new CnDeployError(`vault does not exist: ${vault}`);
  }
  if (!exists(join(vault, ".obsidian"))) {
    throw new CnDeployError(`not an Obsidian vault (no .obsidian/): ${vault}`);
  }
  const target = artifactPath(vault);
  const current = readIfExists(target);
  if (current !== null && !current.startsWith(BANNER_PREFIX)) {
    throw new CnDeployError(
      `refusing to clobber a hand-authored file: ${target}\n` +
        `  it does not start with the generated banner, so it was not produced by \`std cn deploy\`.\n` +
        `  move it aside (e.g. to Scripts/_retired/) and re-run.`,
    );
  }
  return target;
}

/**
 * Bundle `src/cn/index.ts` into a single ESM string with the banner as line 1.
 *
 * `target: "browser"` because the artifact runs inside Obsidian (Electron renderer). Host plugin APIs
 * are structural types only, so nothing external is reachable — a test asserts the output contains no
 * import/require of a non-std specifier (AC4). Exactly one output is expected; more than one means the
 * slice grew a code-split boundary and the one-artifact contract broke — fail loud rather than write a
 * partial bundle.
 *
 * `format` is a parameter because the CST-can-require-ESM question is the assumption Story 7.1 tests
 * live (AC8). If ESM does not load, the pre-authorized fallback is `"cjs"` with target unchanged.
 */
export async function buildBundle(format: "esm" | "cjs" = "esm"): Promise<string> {
  const result = await Bun.build({
    entrypoints: [entrypoint()],
    target: "browser",
    format,
    banner: BANNER,
  });
  if (!result.success) {
    throw new CnDeployError(`bundle failed:\n${result.logs.map(String).join("\n")}`);
  }
  if (result.outputs.length !== 1) {
    throw new CnDeployError(
      `expected exactly 1 bundle output, got ${result.outputs.length} — the one-artifact contract broke`,
    );
  }
  return await result.outputs[0]!.text();
}

/** Injected sink so `run` is testable without capturing stdout. */
export interface CnDeployDeps {
  log?: (line: string) => void;
}

/**
 * `std cn deploy --vault <dir>` — validate, build in memory, write atomically, read back.
 * Returns a process exit code: 0 ok, 1 fail-loud, 2 usage.
 */
export async function runCnDeploy(argv: string[], deps: CnDeployDeps = {}): Promise<number> {
  const log = deps.log ?? ((l: string) => console.log(l));
  const [sub, ...rest] = argv;

  if (sub !== "deploy") {
    console.error("usage: std cn deploy --vault <dir>   # bundle src/cn -> <vault>/Scripts/cn.js");
    return 2;
  }

  const vault = flagValue(rest, "vault");
  let target: string;
  try {
    target = resolveTarget(vault);
  } catch (e) {
    if (e instanceof CnDeployError) {
      console.error(`✗ ${e.message}`);
      // A missing --vault is a USAGE error; everything else is a real failure.
      return vault === undefined || vault === "" ? 2 : 1;
    }
    throw e;
  }

  const format = (flagValue(rest, "format") ?? "esm") as "esm" | "cjs";
  if (format !== "esm" && format !== "cjs") {
    console.error(`✗ --format must be esm or cjs (got '${format}')`);
    return 2;
  }

  try {
    const code = await buildBundle(format);
    atomicWrite(target, code);
    // Read-back verification, the Makefile discipline: never claim a write we did not confirm landed.
    const written = readIfExists(target);
    if (written !== code) {
      throw new CnDeployError(`read-back mismatch at ${target} — the artifact on disk is not what was built`);
    }
    log(`✓ cn (${format}) → ${target}  ${code.length} bytes`);
    return 0;
  } catch (e) {
    if (e instanceof CnDeployError) {
      console.error(`✗ ${e.message}`);
      return 1;
    }
    throw e; // unexpected — fail loud, never swallow (FR5)
  }
}
