// dashkit-deploy — bundle the `src/dashkit/` Obsidian edge into its target vault as a single generated
// artifact.
//
//   std dashkit deploy --vault <dir>   ->   <vault>/Scripts/dashkit.js
//
// THIN SPEC + WIRING over the promoted engine (Story 8.3 D-1). This story exists BECAUSE shipped code named
// `dashkit deploy --watch` as the second caller of `runWatch` (`cn-deploy.test.ts:910`, `:1022`) — so the
// edge-agnostic machinery (watch loop, ignore-list, debounce, build, guards, TOCTOU re-check, skip-if-
// identical, 0/1/2 contract) lives in `./edge-deploy` and is SHARED with cn, never copied. This file supplies
// only dashkit's `EdgeSpec` (banner, artifact name, entrypoint, watched dirs) and the thin cn-parallel surface.
//
// ESM-ONLY (bite #9 / 7.1). CST 13.3.2 loads an ESM `Bun.build` artifact; the cjs experiment is settled and
// NOT re-run here. So dashkit's spec omits `formats` — the engine never parses `--format` for it and always
// builds esm. The one pre-authorized fallback (a `target:"bun"` build) is NOT invented speculatively (D-3);
// AC7 proves the browser-target bundle loads under bare bun by execution, and only a real failure would earn it.
//
// PREFLIGHT (Story 8.4, AC5). dashkit's plugin contract + the shared `verifyPlugins` + `dashkit verify` land
// in 8.4, and this spec FILLS 8.3's `EdgeSpec.preflight` hook (no second seam): `dashkit deploy` runs the
// envelope check against the target vault BEFORE building, so an `error` finding (a missing foundation)
// aborts with exit 1 having written NOTHING, and under `--watch` the watcher never registers. `core` IS in
// this bundle (bite #4): a `src/core/**` edit WRITES and the bytes change, the inverse of cn's "imports
// nothing from core" contact observation.
//
// ONE-WAY (AD-5, GIT-SoT / D-6). `src/dashkit/` is the source of truth; the target vault holds build
// output only. The artifact carries dashkit's generated banner, and deploy REFUSES to clobber a target that
// lacks THAT prefix — a cn-bannered file does not satisfy it, and vice versa (the guard is per-edge, never a
// shared literal). The hand-authored, freeze-EXEMPT `Scripts/dashkit.config.ts` is never a deploy target (D-4).
//
// IDENTITY-FREE (D4/NFR3). No vault path, vault name, or consumer literal appears here or anywhere in
// `src/**` — not even in a comment (AC5's own grep reads the raw source). The path arrives only as `--vault`;
// Pedro's actual path lives caller-side, and the target vault's name is on the check:no-consumer-ids denylist.

import { join } from "node:path";

import { DASHKIT_PLUGIN_CONTRACT } from "../dashkit/plugins";
import { verifyPlugins } from "../core/plugin-contract";
import { DashkitVerifyError, readVaultPlugins, renderFindings } from "./dashkit-verify";
import {
  type DeployResult,
  type EdgeDeployDeps,
  type EdgeSpec,
  EdgeDeployError,
  type WatchHandle,
  WATCH_DEBOUNCE_MS,
  artifactPath as edgeArtifactPath,
  buildBundle as edgeBuildBundle,
  deployOnce as edgeDeployOnce,
  isBundleRelevant,
  makeWatchAdapter,
  resolveTarget as edgeResolveTarget,
  runEdgeDeploy,
  runWatch,
} from "./edge-deploy";

/** Marker every generated artifact starts with — the clobber guard keys on this exact (dashkit-specific) prefix. */
export const BANNER_PREFIX = "// GENERATED by `std dashkit deploy`";

/** Line 1 of every artifact. Emitted via Bun.build's `banner`, so it is inside the build's determinism. */
export const BANNER =
  `${BANNER_PREFIX} from std/src/dashkit — do not edit. Edit std/src/dashkit and redeploy.`;

/** dashkit's error type, an alias of the promoted `EdgeDeployError` (the SAME class the engine throws). */
export { EdgeDeployError as DashkitDeployError };

// Re-export the generic engine surface dashkit's tests and main.ts import from `./dashkit-deploy`.
export { WATCH_DEBOUNCE_MS, isBundleRelevant, makeWatchAdapter, runWatch };
export type { DeployResult, WatchHandle };
/** The deps shape main.ts threads through for the `dashkit deploy --watch` callsite. */
export type DashkitDeployDeps = EdgeDeployDeps;

/**
 * Run dashkit's plugin-envelope contract against the target vault BEFORE building (8.4 AC5) — declared ≠
 * decorative. The exact sibling of cn's `preflightVault`, wired to dashkit's contract + edge label.
 *
 * An `error` finding means a required foundation (CodeScript Toolkit, JS Engine, or Dataview) is missing,
 * disabled, or registered-but-not-installed. Deploying a bundle the loader cannot `require`, or that no
 * js-engine block can render, is a guaranteed dead dashboard — so this throws and the caller aborts with
 * exit 1 having written NOTHING (fail-loud, FR5). `warn`/`info` findings are returned as lines to print;
 * drift never blocks a deploy (AD-6: no hard version-pins).
 *
 * IMPORT EDGE: this reaches `src/dashkit/plugins.ts` (pure data) + `src/core/plugin-contract.ts` (the pure
 * comparator) via `dashkit-verify`'s reader. It never imports `src/dashkit/index.ts`, which would drag DOM
 * types into the Bun typecheck graph — and it never imports `src/cn/**` (AD-8).
 *
 * ONCE PER INVOCATION, never per rebuild: the engine calls `spec.preflight` ahead of the first build, so
 * `--watch` preflights at startup only. The plugin set does not change on a source save, and re-reading the
 * vault on every keystroke would hammer iCloud.
 */
export function preflightVault(vault: string): string[] {
  let findings;
  try {
    findings = verifyPlugins(readVaultPlugins(vault), DASHKIT_PLUGIN_CONTRACT, "dashkit");
  } catch (e) {
    // Re-badge so the caller's single `EdgeDeployError` catch keeps the 0/1/2 contract. The guards are
    // the same guards `resolveTarget` already ran, plus this command's own community-plugins.json ones.
    throw e instanceof DashkitVerifyError ? new EdgeDeployError(e.message) : e;
  }
  const errors = findings.filter((f) => f.severity === "error");
  if (errors.length > 0) {
    throw new EdgeDeployError(
      `plugin envelope check failed — refusing to deploy into ${vault}\n` +
        renderFindings(errors)
          .map((l) => (l === "" ? l : `  ${l}`)) // never indent the blank separator into whitespace
          .join("\n"),
    );
  }
  return renderFindings(findings.filter((f) => f.severity !== "ok"));
}

/** The `src/dashkit/index.ts` entrypoint, resolved relative to THIS file — never a hardcoded absolute path. */
export function entrypoint(): string {
  return join(import.meta.dir, "..", "dashkit", "index.ts");
}

/** The directories the bundle MAY contain (AD-5 rule 2), resolved relative to THIS file — never absolute.
 *  `src/core` is watched because `core` IS in the dashkit bundle (bite #4) — a core edit rebuilds and the
 *  bytes DO change, unlike cn where a core edit logs `· unchanged`. */
export function watchDirs(): string[] {
  return [join(import.meta.dir, "..", "dashkit"), join(import.meta.dir, "..", "core")];
}

/**
 * dashkit's `EdgeSpec`: the only thing the promoted engine needs to build/watch/deploy the dashkit edge.
 * The banner prefix is dashkit-SPECIFIC (never a shared literal) so a cn artifact cannot satisfy dashkit's
 * clobber guard and vice versa. No `formats` (esm-only). The `preflight` fills 8.3's hook (8.4 AC5).
 */
export const DASHKIT_SPEC: EdgeSpec = {
  name: "dashkit",
  artifact: "dashkit.js",
  entrypoint: entrypoint(),
  watchDirs: watchDirs(),
  bannerPrefix: BANNER_PREFIX,
  banner: BANNER,
  usage:
    "usage: std dashkit deploy --vault <dir> [--watch]   # bundle src/dashkit -> <vault>/Scripts/dashkit.js\n" +
    "       std dashkit verify --vault <dir>             # check the vault against dashkit's plugin envelope",
  preflight: preflightVault,
};

/** Where the bundle lands inside a vault. Pure — no fs touched. */
export function artifactPath(vault: string): string {
  return edgeArtifactPath(DASHKIT_SPEC, vault);
}

/**
 * Validate that `vault` is a usable Obsidian vault and that the target is safe to overwrite, then return
 * the artifact path (see the engine's `resolveTarget` for the full fail-loud contract).
 */
export function resolveTarget(vault: string | undefined): string {
  return edgeResolveTarget(DASHKIT_SPEC, vault);
}

/** Bundle `src/dashkit/index.ts` (esm only) with dashkit's banner as line 1 (see the engine's buildBundle). */
export function buildBundle(entry: string = entrypoint()): Promise<string> {
  return edgeBuildBundle(DASHKIT_SPEC, "esm", entry);
}

/** One full deploy cycle for dashkit (see the engine's deployOnce for skip-if-identical / read-back). */
export function deployOnce(vault: string, entry: string = entrypoint()): Promise<DeployResult> {
  return edgeDeployOnce(DASHKIT_SPEC, vault, "esm", entry);
}

/**
 * `std dashkit deploy --vault <dir> [--watch]` — validate, build in memory, write atomically, read back.
 * With `--watch`, the same deploy stays resident and re-runs on every save under `src/dashkit` + `src/core`.
 * Returns a process exit code: 0 ok, 1 fail-loud, 2 usage. A thin delegate to the promoted engine (D-1).
 */
export function runDashkitDeploy(argv: string[], deps: DashkitDeployDeps = {}): Promise<number> {
  return runEdgeDeploy(DASHKIT_SPEC, argv, deps);
}
