// notekit-deploy — bundle the `src/notekit/` Obsidian edge into its target vault as a single generated
// artifact.
//
//   std notekit deploy --vault <dir>   ->   <vault>/Scripts/notekit.js
//
// THIN SPEC + WIRING over the shared engine (Story 1.4, cloning Story 8.3's D-1). Everything
// edge-agnostic — the watch loop, the ignore-list, the debounce, the build, the guards, the TOCTOU
// re-check, skip-if-identical, the 0/1/2 exit contract — lives in `./edge-deploy` and is SHARED with cn
// and dashkit. This file supplies only notekit's `EdgeSpec` and the thin sibling surface. The shape is
// CLONED from `dashkit-deploy.ts`, never imported from it: two edges of the same vault must not form a
// module edge (AD-8).
//
// ⚠️-1 — THE ENTRYPOINT IS THE EDGE BARREL, NOT THE PACKAGE BARREL. notekit is the estate's first MIXED
// pure/edge slice: `src/notekit/index.ts` is the `"./notekit"` exports entry (pure surface + the config
// type, root-typechecked, DOM-free) and `src/notekit/edge/index.ts` is the DOM half. The bundle must
// start at the EDGE barrel, and it is named here BY PATH — `Bun.build` follows it without any
// root-typechecked file ever importing `edge/**`, which is what keeps `document` out of the root
// program. Pointing this at `src/notekit/index.ts` would build a bundle with no renderer in it.
//
// ⚠️-2 — `preflight` IS OMITTED DELIBERATELY, NOT FORGOTTEN. `EdgeSpec.preflight` is optional
// (`edge-deploy.ts:60`) and the engine calls it only when present. cn and dashkit both fill it with a
// plugin-envelope check; notekit v1 does not, because the notekit plugin contract and `notekit verify`/
// `doctor` are FR18 (Epic 3) — outside Epic 1's FR set (FR12/13/14). Deploy without a preflight is
// sound: a missing JS Engine yields a dead render, which FR18's `doctor` addresses later. Do NOT invent
// a `src/notekit/plugins.ts` + preflight here; that is a scope leak into a later epic.
//
// ESM-ONLY. The vault's loader loads an ESM `Bun.build` artifact, so this spec omits `formats` — the
// engine then never parses `--format` for notekit and always builds esm. No invented cjs optionality.
//
// ONE-WAY (AD-5, GIT-SoT / D5). `src/notekit/` is the source of truth; the target vault holds build
// output only. The artifact carries notekit's OWN generated banner, and deploy REFUSES to clobber a
// target that lacks THAT prefix — a dashkit- or cn-bannered file does not satisfy it, and vice versa.
// The guard is per-edge and there is no shared prefix anywhere: widening it would be the same act as
// narrowing it. The hand-authored, freeze-EXEMPT `notekit.config.ts` is never a deploy target (D4).
//
// IDENTITY-FREE (D4/NFR3). No vault path, vault name, or consumer literal appears here or anywhere in
// `src/**`. The path arrives only as `--vault`; the operator's actual path lives caller-side.

import { join } from "node:path";

import {
  type DeployResult,
  type EdgeDeployDeps,
  type EdgeSpec,
  EdgeDeployError,
  type WatchHandle,
  WATCH_DEBOUNCE_MS,
  artifactPath as edgeArtifactPath,
  buildBundle as edgeBuildBundle,
  deployOnce as edgeDeployOnce,
  isBundleRelevant,
  makeWatchAdapter,
  resolveTarget as edgeResolveTarget,
  runEdgeDeploy,
  runWatch,
} from "./edge-deploy";

/** Marker every generated artifact starts with — the clobber guard keys on this exact (notekit-specific) prefix. */
export const BANNER_PREFIX = "// GENERATED by `std notekit deploy`";

/** Line 1 of every artifact. Emitted via Bun.build's `banner`, so it is inside the build's determinism. */
export const BANNER =
  `${BANNER_PREFIX} from std/src/notekit — do not edit. Edit std/src/notekit and redeploy.`;

/** notekit's error type, an alias of the shared `EdgeDeployError` (the SAME class the engine throws). */
export { EdgeDeployError as NotekitDeployError };

// Re-export the generic engine surface notekit's tests and main.ts import from `./notekit-deploy`.
export { WATCH_DEBOUNCE_MS, isBundleRelevant, makeWatchAdapter, runWatch };
export type { DeployResult, WatchHandle };
/** The deps shape main.ts threads through for the `notekit deploy --watch` callsite. */
export type NotekitDeployDeps = EdgeDeployDeps;

/**
 * The `src/notekit/edge/index.ts` entrypoint, resolved relative to THIS file — never a hardcoded
 * absolute path (D4).
 *
 * ⚠️-1: `edge/index.ts`, NOT `index.ts`. See the file header — the package barrel carries no renderer.
 */
export function entrypoint(): string {
  return join(import.meta.dir, "..", "notekit", "edge", "index.ts");
}

/** The directories the bundle MAY contain (AD-5 rule 2), resolved relative to THIS file — never absolute.
 *  `src/core` is watched because `core` IS in the notekit bundle (the pure `core-*` files import
 *  `classify` from it), so a `src/core` edit rebuilds and the bytes DO change — same as dashkit. */
export function watchDirs(): string[] {
  return [join(import.meta.dir, "..", "notekit"), join(import.meta.dir, "..", "core")];
}

/**
 * notekit's `EdgeSpec`: the only thing the shared engine needs to build/watch/deploy the notekit edge.
 * The banner prefix is notekit-SPECIFIC (never a shared literal) so a cn or dashkit artifact cannot
 * satisfy notekit's clobber guard and vice versa. No `formats` (esm-only). No `preflight` (⚠️-2).
 */
export const NOTEKIT_SPEC: EdgeSpec = {
  name: "notekit",
  artifact: "notekit.js",
  entrypoint: entrypoint(),
  watchDirs: watchDirs(),
  bannerPrefix: BANNER_PREFIX,
  banner: BANNER,
  usage:
    "usage: std notekit deploy --vault <dir> [--watch]   # bundle src/notekit -> <vault>/Scripts/notekit.js",
};

/** Where the bundle lands inside a vault. Pure — no fs touched. */
export function artifactPath(vault: string): string {
  return edgeArtifactPath(NOTEKIT_SPEC, vault);
}

/**
 * Validate that `vault` is a usable Obsidian vault and that the target is safe to overwrite, then
 * return the artifact path (see the engine's `resolveTarget` for the full fail-loud contract).
 */
export function resolveTarget(vault: string | undefined): string {
  return edgeResolveTarget(NOTEKIT_SPEC, vault);
}

/** Bundle `src/notekit/edge/index.ts` (esm only) with notekit's banner as line 1. */
export function buildBundle(entry: string = entrypoint()): Promise<string> {
  return edgeBuildBundle(NOTEKIT_SPEC, "esm", entry);
}

/** One full deploy cycle for notekit (see the engine's deployOnce for skip-if-identical / read-back). */
export function deployOnce(vault: string, entry: string = entrypoint()): Promise<DeployResult> {
  return edgeDeployOnce(NOTEKIT_SPEC, vault, "esm", entry);
}

/**
 * `std notekit deploy --vault <dir> [--watch]` — validate, build in memory, write atomically, read
 * back. With `--watch`, the same deploy stays resident and re-runs on every save under `src/notekit` +
 * `src/core`. Returns a process exit code: 0 ok, 1 fail-loud, 2 usage. A thin delegate to the shared
 * engine.
 */
export function runNotekitDeploy(argv: string[], deps: NotekitDeployDeps = {}): Promise<number> {
  return runEdgeDeploy(NOTEKIT_SPEC, argv, deps);
}
