import { describe, expect, test } from "bun:test";
import { existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import {
  NAV_NAME_GRAMMAR,
  RepoNavError,
  defaultTargets,
  generateRepoNav,
  generateStdCompletion,
  installAlias,
  runAlias,
  validateRegistry,
  type RepoConfig,
} from "./index";

const cfg: RepoConfig = {
  entries: { zp: "$HOME/Dev/zsh-planning", mph: "$HOME/Sites/melb-print-hub", std: "$HOME/Dev/std" },
  reserved: ["std"],
};

describe("validateRegistry — fail-loud guards (AC2)", () => {
  test("accepts a clean registry and returns sorted, reserved-excluded cd-alias keys", () => {
    expect(validateRegistry(cfg)).toEqual(["mph", "zp"]); // sorted; 'std' reserved → excluded
  });

  test("fail-loud on a grammar violation, naming the offender", () => {
    const bad: RepoConfig = { entries: { "bad name": "/x" } };
    expect(() => validateRegistry(bad)).toThrow(RepoNavError);
    expect(() => validateRegistry(bad)).toThrow(/'bad name' violates the naming grammar/);
  });

  test("fail-loud on a frozen-name collision", () => {
    const frozen = new Set(["forge", "agent"]);
    const collide: RepoConfig = { entries: { forge: "/x", zp: "/y" } };
    expect(() => validateRegistry(collide, frozen)).toThrow(/'forge' collides with a frozen callable/);
  });

  test("a reserved alias is NOT checked for frozen collision (reachable via `repo <name>`)", () => {
    const frozen = new Set(["std"]);
    expect(() => validateRegistry(cfg, frozen)).not.toThrow(); // 'std' is reserved → skipped
  });

  test("the grammar matches zshstd callable names and rejects spaces/empties", () => {
    expect(NAV_NAME_GRAMMAR.test("gh-pr-view")).toBe(true);
    expect(NAV_NAME_GRAMMAR.test("nlm_zsh")).toBe(true);
    expect(NAV_NAME_GRAMMAR.test("a b")).toBe(false);
    expect(NAV_NAME_GRAMMAR.test("")).toBe(false);
  });
});

describe("generateRepoNav — deterministic, sorted, complete (AC1)", () => {
  const out = generateRepoNav(cfg);

  test("is byte-identical on regeneration (GIT-SoT reproducibility)", () => {
    expect(generateRepoNav(cfg)).toBe(out);
  });

  test("emits entries in sorted key order", () => {
    const block = out.slice(out.indexOf("ZSH_REPOS=("), out.indexOf(")", out.indexOf("ZSH_REPOS=(")));
    const keys = block
      .split("\n")
      .map((l) => l.match(/^\s+(\S+)\s+"/)?.[1])
      .filter((k): k is string => Boolean(k));
    expect(keys).toEqual(["mph", "std", "zp"]); // sorted
  });

  test("carries the generated banner + ZSH_REPOS + repo/repos functions", () => {
    expect(out).toContain("GENERATED by `std alias --install`");
    expect(out).toContain("typeset -gA ZSH_REPOS=(");
    expect(out).toContain("repo() {");
    expect(out).toContain("repos() {");
    expect(out).toContain("compdef _repo repo");
  });

  test("injects the reserved names into the cd-alias skip-list (no hardcoded consumer names)", () => {
    expect(out).toContain("local -a reserved=(std)");
  });

  test("a bad registry throws before producing any output (fail-closed)", () => {
    expect(() => generateRepoNav({ entries: { "x y": "/z" } })).toThrow(RepoNavError);
  });
});

describe("generateStdCompletion — derived from the command surface (AC1)", () => {
  test("deterministic, sorted, _describe shape", () => {
    const c1 = generateStdCompletion(["gates", "brief", "alias"]);
    const c2 = generateStdCompletion(["alias", "brief", "gates"]); // different order in
    expect(c1).toBe(c2); // → identical out (sorted)
    expect(c1).toContain("#compdef std");
    expect(c1).toContain("_describe 'std command' cmds");
    expect(c1.indexOf("'alias'")).toBeLessThan(c1.indexOf("'brief'")); // sorted
  });

  test("dedupes repeated command names", () => {
    expect(generateStdCompletion(["gates", "gates"]).match(/'gates'/g)?.length).toBe(1);
  });
});

describe("installAlias — deploy to targets, fail-loud writes nothing (AC1)", () => {
  test("writes both artifacts, creating parent dirs", () => {
    const root = mkdtempSync(join(tmpdir(), "std-install-"));
    try {
      const targets = defaultTargets(join(root, "zsh"));
      const res = installAlias({ config: cfg, commands: ["gates", "alias"], targets });
      expect(existsSync(res.repoNavPath)).toBe(true);
      expect(existsSync(res.completionPath)).toBe(true);
      expect(readFileSync(res.repoNavPath, "utf-8")).toContain("typeset -gA ZSH_REPOS=(");
      expect(readFileSync(res.completionPath, "utf-8")).toContain("#compdef std");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("a fail-loud registry writes NOTHING (validation precedes any write)", () => {
    const root = mkdtempSync(join(tmpdir(), "std-install-"));
    try {
      const targets = defaultTargets(join(root, "zsh"));
      expect(() =>
        installAlias({ config: { entries: { "bad name": "/x" } }, commands: ["gates"], targets }),
      ).toThrow(RepoNavError);
      // nothing was deployed
      expect(existsSync(join(root, "zsh"))).toBe(false);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("defaultTargets places artifacts under the ZDOTDIR functions/completions homes", () => {
    const t = defaultTargets("/x/.config/zsh");
    expect(t.repoNavPath).toBe("/x/.config/zsh/functions/repo-nav.zsh");
    expect(t.completionPath).toBe("/x/.config/zsh/completions/_std");
  });
});

describe("runAlias — the std-cli `alias` command (AC1)", () => {
  test("--install deploys and reports both paths, exit 0", () => {
    const root = mkdtempSync(join(tmpdir(), "std-alias-"));
    try {
      const lines: string[] = [];
      const code = runAlias(["--install"], {
        config: cfg,
        commands: ["gates", "alias"],
        targets: defaultTargets(join(root, "zsh")),
        log: (l) => lines.push(l),
      });
      expect(code).toBe(0);
      expect(lines.some((l) => l.includes("repo-nav.zsh"))).toBe(true);
      expect(lines.some((l) => l.includes("_std"))).toBe(true);
      expect(existsSync(join(root, "zsh", "functions", "repo-nav.zsh"))).toBe(true);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("a fail-loud registry returns exit 1 and writes nothing", () => {
    const root = mkdtempSync(join(tmpdir(), "std-alias-"));
    try {
      const code = runAlias(["--install"], {
        config: { entries: { "bad name": "/x" } },
        commands: ["gates"],
        targets: defaultTargets(join(root, "zsh")),
        log: () => {},
      });
      expect(code).toBe(1);
      expect(existsSync(join(root, "zsh"))).toBe(false);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("without --install prints usage, exit 2, deploys nothing", () => {
    const lines: string[] = [];
    const code = runAlias([], {
      config: cfg,
      commands: ["gates"],
      targets: defaultTargets("/should/not/be/written"),
      log: (l) => lines.push(l),
    });
    expect(code).toBe(2);
    expect(lines.join("\n")).toMatch(/usage: std alias --install/);
    expect(existsSync("/should/not/be/written")).toBe(false);
  });
});
