// Story 4.5 — the AD-7 repo-nav generator + `_std` completion + `alias --install`.
//
// ONE source, TWO outputs (AD-7): `~/.config/std/repos.ts` (the user's registry) is the single source
// of truth; the generated `repo-nav.zsh` and `_std` completion are DEPLOY ARTIFACTS — one-way output,
// never hand-edited (GIT-SoT). Edit the source, regenerate, deploy.
//
// Identity-free (D4/NFR3): std bakes in NO consumer data. The registry entries, the reserved CLI names
// (e.g. the consumer's own command names), and the frozen-name set are all PASSED IN — std owns the
// generator + the schema, the user owns the data, the consumer (zsh-planning) owns the grammar oracle.
//
// Bun edge — fs/os/path are fine here; core stays pure.

import { join } from "node:path";

import { atomicWrite } from "../fsx";
// Intra-slice, so no spine rule is engaged: the fenced edge is `src/bmad/cli.ts → src/cli/surface.ts`
// (BM-20), which this story does not widen.
import {
  flagEnum,
  renderAliasUsage,
  type CommandSurface,
  type FlagSpec,
  type FlagValueSource,
} from "./surface";

/** The registry: a map of nav alias → target path (the path string is emitted verbatim into zsh, so a
 *  consumer may use `$HOME`/`~` and zsh expands it at source time). */
export type RepoRegistry = Record<string, string>;

/** The user's `~/.config/std/repos.ts` contract. `reserved` names are CLI commands that must never be
 *  shadowed by a generated cd-alias (reachable via `repo <name>` instead). */
export interface RepoConfig {
  entries: RepoRegistry;
  reserved?: string[];
  /** Optional frozen callable names a generated alias must never collide with (the consumer supplies
   *  these — std bakes in no consumer's frozen set). Absent → only grammar/reserved/owned checks run. */
  frozen?: string[];
}

/** zshstd's callable-name grammar (mirrors `fn-names.zsh`: a name matches this, public = not `_`-led).
 *  A generated nav name must conform — the generator fails loud otherwise (AD-7). */
export const NAV_NAME_GRAMMAR = /^[A-Za-z0-9_:.-]+$/;

/** Raised on a grammar violation or a frozen-name collision — the AD-7 fail-loud guards. */
export class RepoNavError extends Error {}

/** The generator's OWN public/private function names — it owns this namespace (these are the artifact,
 *  not cd-aliases), so they are exempt from the cd-alias frozen-collision check. */
const OWNED_NAMES = ["repo", "repos", "_repo"] as const;

/**
 * Validate the registry against the grammar + the injected frozen set, fail-LOUD (AD-7):
 *   - every alias must match `NAV_NAME_GRAMMAR` (else a grammar violation);
 *   - no alias may collide with a frozen callable name (else it would shadow it).
 * Returns the cd-alias keys to emit (sorted, reserved excluded), or throws `RepoNavError`.
 */
export function validateRegistry(
  config: RepoConfig,
  frozenNames: ReadonlySet<string> = new Set(),
): string[] {
  const reserved = new Set(config.reserved ?? []);
  const keys = Object.keys(config.entries).sort();
  for (const key of keys) {
    if (!NAV_NAME_GRAMMAR.test(key)) {
      throw new RepoNavError(
        `repo-nav: alias '${key}' violates the naming grammar ${NAV_NAME_GRAMMAR} (AD-7)`,
      );
    }
    if (key.startsWith("_")) {
      throw new RepoNavError(
        `repo-nav: alias '${key}' starts with '_' — nav aliases are public names (AD-7), not private`,
      );
    }
    if ((OWNED_NAMES as readonly string[]).includes(key)) {
      throw new RepoNavError(
        `repo-nav: alias '${key}' is reserved by the generator (it defines ${OWNED_NAMES.join("/")}) — ` +
          `choose another alias`,
      );
    }
    // A reserved CLI name is reachable via `repo <name>`, never a cd-alias — so it never shadows, and is
    // not checked for collision. Every OTHER alias must not collide with a frozen callable name.
    if (!reserved.has(key) && frozenNames.has(key)) {
      throw new RepoNavError(
        `repo-nav: alias '${key}' collides with a frozen callable name — generated names must never ` +
          `shadow the frozen set (AD-7). Rename the entry or reserve it.`,
      );
    }
  }
  return keys.filter((k) => !reserved.has(k));
}

const GENERATED_BANNER =
  "# repo-nav.zsh — GENERATED by `std alias --install` from ~/.config/std/repos.ts (AD-7).\n" +
  "# ONE source, TWO outputs. Do NOT hand-edit — edit repos.ts and regenerate. Generated artifacts\n" +
  "# are never frozen (the name surface lives in the source registry).";

// The static behavior (repo/repos/_repo + cd-alias block) is constant — only ZSH_REPOS and the reserved
// skip-list are data-driven. `reserved` is interpolated directly (no placeholder, so nothing in the body
// can accidentally collide with a magic token).
function repoNavBody(reserved: readonly string[]): string {
  const reservedList = reserved.slice().sort().join(" ");
  return `
# repo <alias> — cd to a registered repo (never shadows a command; tab-completes)
repo() {
  emulate -L zsh
  local key="$1"
  if [[ -z "$key" || -z "\${ZSH_REPOS[$key]}" ]]; then
    print -u2 "repo: unknown '\${key:-}'. Known: \${(ok)ZSH_REPOS}"; return 1
  fi
  cd "\${ZSH_REPOS[$key]}"
}

# repos — list the registry (alias · name · path). The name is the path basename; it is colorized on a
# TTY only (plain when piped/headless, so the listing stays byte-identical in a pipe). Path is \$HOME-shortened.
repos() {
  emulate -L zsh
  local k name disp col='' rst=''; local -i w=0
  [[ -t 1 && -z \${NO_COLOR:-} ]] && { col=$'\\e[36m'; rst=$'\\e[0m'; }
  for k in \${(ok)ZSH_REPOS}; do name="\${ZSH_REPOS[$k]:t}"; (( \${#name} > w )) && w=\${#name}; done
  for k in \${(ok)ZSH_REPOS}; do
    name="\${ZSH_REPOS[$k]:t}"
    disp="\${ZSH_REPOS[$k]/#\$HOME/~}"   # quoted: unquoted, zsh re-tilde-expands ~ back to \$HOME
    printf '  %-7s %s%-*s%s  %s\\n' "$k" "$col" "$w" "$name" "$rst" "$disp"
  done
}

# tab-completion for \`repo\`
_repo() { local -a k; k=(\${(ok)ZSH_REPOS}); compadd -a k }
compdef _repo repo 2>/dev/null

# Direct cd-aliases — generated from the registry, but NEVER shadow a real command.
() {
  emulate -L zsh
  local k; local -a reserved=(${reservedList})
  for k in \${(k)ZSH_REPOS}; do
    (( \${reserved[(I)$k]} )) && continue                 # reserved CLI name → skip
    command -v "$k" >/dev/null 2>&1 && continue          # a real command owns it → skip
    alias "$k"="cd \${(q)ZSH_REPOS[$k]}"
  done
}
`;
}

/**
 * Generate the `repo-nav.zsh` artifact from the registry. DETERMINISTIC — entries are emitted in their
 * `repos.ts` DECLARATION order (object key order is stable, so regeneration is still byte-identical,
 * GIT-SoT reproducibility) and that order is the user's, preserving their priority. (Runtime listing via
 * `repos`/completion is independently alphabetical — zsh's `${(ok)…}` sorts on access.) Validates first.
 */
export function generateRepoNav(
  config: RepoConfig,
  frozenNames: ReadonlySet<string> = new Set(),
): string {
  validateRegistry(config, frozenNames);
  const reserved = config.reserved ?? [];
  const keys = Object.keys(config.entries); // declaration order — the user's priority, preserved
  const width = keys.reduce((w, k) => Math.max(w, k.length), 0);
  const rows = keys.map((k) => `  ${k.padEnd(width)}  "${config.entries[k]}"`).join("\n");
  return `${GENERATED_BANNER}\n\ntypeset -gA ZSH_REPOS=(\n${rows}\n)\n${repoNavBody(reserved)}`;
}

// ── the `_std` completion emitter (3.2) ───────────────────────────────────────────────────────────
// Two levels, from the ONE surface model (3.1). Before this the generator was handed `commands:
// ["alias"]` — a hardcoded literal that was the entire command list `_std` would ever know (D-a) — and
// emitted a single flat `_describe` with nowhere to express `std bmad verify --json` (D-b). Both close
// here: the surface is a parameter, and the emitted shape is the `_arguments -C` state machine.
//
// ESCAPING IS A FUNCTION, NOT A HOPEFUL `.replace` CHAIN, and it is load-bearing on shipped data TODAY:
// `bmad deploy`'s desc carries an apostrophe ("the estate's leg"), as does `cn verify`'s ("cn's declared
// plugin envelope"). Both land inside single-quoted zsh words, and an unescaped one makes the artifact
// fail to parse at all (`zsh -n` → `unmatched '`). The two contexts escape DIFFERENTLY, so there are two
// helpers, each tested against a hostile fixture rather than against the happy path.

/**
 * The first line of a model description.
 *
 * A `\n` in a `desc` is HELP's continuation-row device — `surface.ts`'s `row()` renders it as a second
 * line indented to the description column — not part of the sentence. Two shipped descs carry one
 * (`cn`/`dashkit` `verify --vault`). A zsh explanation is a one-line hint, so the continuation is
 * dropped rather than folded in: `zsh -n` accepts an embedded newline inside `'…'`, so this is a
 * legibility rule the syntax check would never have caught.
 */
function oneLine(desc: string): string {
  return desc.split("\n")[0]!;
}

/** `'` → `'\''`: close the quote, emit a literal apostrophe, reopen. The only form that survives `'…'`. */
function sq(text: string): string {
  return text.replace(/'/g, "'\\''");
}

/**
 * One `_describe` entry — `'name:description'`.
 *
 * A literal colon in the completion NAME is backslash-escaped (`man zshcompsys`: *"Any literal colons in
 * completion must be quoted with a backslash"* — zsh's own `_git` does exactly this at `:3091`). Every
 * name in the surface is `[a-z]+` today, so the rule is future-proofing and is asserted as such. A colon
 * in the DESCRIPTION is left alone: only the first colon splits the entry.
 */
export function describeEntry(name: string, desc: string): string {
  const escapedName = name.replace(/\\/g, "\\\\").replace(/:/g, "\\:");
  return `'${sq(escapedName)}:${sq(oneLine(desc))}'`;
}

/** `<dir>` → `dir`. `metavar` is a DISPLAY string (HELP renders `--vault <dir>`); zsh wants the bare word. */
function messageOf(metavar: string): string {
  return metavar.replace(/^</, "").replace(/>$/, "").replace(/:/g, "\\:");
}

/**
 * The zsh reader each `FlagValueSource` maps to. EMITTER vocabulary, not model data — the model says
 * `estate.repos`, the emitter picks the function name. A `Record` over the union rather than a lookup
 * with a fallback, so adding a third source is a compile error here instead of a silently empty action.
 */
const READER_FN: Record<FlagValueSource, string> = {
  "estate.repos": "_std_estate_repos",
  "estate.tools": "_std_estate_tools",
};

/**
 * The `:message:action` tail. Derived from the model's orthogonal fields — `metavar` (display), `value`
 * (semantic) and `source` (where the values live) — never from one another. A `bool` flag takes no value
 * and gets no tail at all. A `list` flag with no `source` still emits an EMPTY action: `--skills` and
 * `--set` have no enumerable vocabulary, so there is nothing to read.
 */
function argTail(flag: FlagSpec, enumValues: readonly string[] | undefined): string {
  if (flag.arity !== "value") return "";
  const message = messageOf(flag.metavar ?? "arg");
  if (flag.value === "path") return `:${message}:_files -/`;
  if (flag.value === "enum") return `:${message}:(${(enumValues ?? flag.enum ?? []).join(" ")})`;
  if (flag.source !== undefined) return `:${message}:_std_list ${READER_FN[flag.source]}`;
  return `:${message}:`;
}

/**
 * One `_arguments` optspec — `'[*]--flag[explanation]:message:action'`.
 *
 * Inside the bracketed explanation, `\`, `[` and `]` are escaped (a bare `]` closes the explanation
 * early — and `zsh -n` does NOT catch that; it exits 0 and misparses only at completion time). A colon
 * is deliberately NOT escaped there: zsh's own `_git:1578` ships
 * `'--signoff[add Signed-off-by: trailer to the commit message]'`, and the man page's colon rule names
 * the optname, message and action — not the explanation, which `]` already delimits.
 */
export function argSpec(flag: FlagSpec, enumValues?: readonly string[]): string {
  const explanation = oneLine(flag.desc)
    .replace(/\\/g, "\\\\")
    .replace(/[[\]]/g, "\\$&");
  const star = flag.repeatable ? "*" : "";
  return `'${sq(`${star}${flag.name}[${explanation}]${argTail(flag, enumValues)}`)}'`;
}

/**
 * A `defaults` entry lands in the artifact as a BARE ZSH WORD, not inside a quoted spec — the reader body
 * is plain zsh, so `describeEntry`/`argSpec`'s escaping never reaches it. One containing a space or a
 * quote would word-split silently into two completions, which `zsh -n` accepts and no probe assertion
 * sees. Hence a charset the emitter FAILS LOUD on rather than a hope.
 */
const DEFAULT_WORD = /^[A-Za-z0-9._-]+$/;

/** Every `defaults` value declared for `source`, deduped in first-seen order. Fail-loud on a bad word. */
function estateDefaults(surface: CommandSurface, source: FlagValueSource): string[] {
  const out: string[] = [];
  for (const cmd of surface.commands) {
    const flags = [...(cmd.flags ?? []), ...cmd.subcommands.flatMap((s) => s.flags)];
    for (const flag of flags) {
      if (flag.source !== source) continue;
      for (const value of flag.defaults ?? []) {
        if (!DEFAULT_WORD.test(value)) {
          throw new RepoNavError(
            `_std: default '${value}' for ${flag.name} is not a bare zsh word ${DEFAULT_WORD} — it ` +
              `would word-split into several completions`,
          );
        }
        if (!out.includes(value)) out.push(value);
      }
    }
  }
  return out;
}

/**
 * The caller-local estate readers, emitted between the banner and `_std()`.
 *
 * std emits the READER, never the names (D4/NFR3) — the values resolve from the caller's own estate file
 * at completion time, and this generator never opens it. The only data interpolated here is the `--tools`
 * flag's `defaults`, which is std's own vocabulary rather than any consumer's.
 *
 * A line scanner, not a TOML parser: it reads `path`/`name`/`tools` out of `[[repos]]` blocks and nothing
 * else. A multi-line `tools = [ … ]` array drops its declared tools; a value spanning lines is not read.
 * Every ceiling degrades to FEWER completions and none errors the shell — which is the property that
 * matters at a `<TAB>`, and it is pinned by tests rather than left to chance.
 */
function estateReaderBlock(surface: CommandSurface): string {
  const toolDefaults = estateDefaults(surface, "estate.tools");
  const toolWords = toolDefaults.length > 0 ? ` ${toolDefaults.join(" ")}` : "";
  return `# --- caller-local estate readers -------------------------------------------------------------------
# std emits the READER, never the names (D4/NFR3). Values resolve from the caller's estate file at
# completion time. A missing/unreadable/malformed file yields no completions and never errors the shell.
# \`source-only\` entries ARE offered: selectRepos excludes them from the DEFAULT set only — naming one
# explicitly is the one way to reach it (src/bmad/manifest.ts). Do not filter them.
_std_estate_values() {
  emulate -L zsh
  setopt extendedglob
  local what=$1
  local f="\${XDG_CONFIG_HOME:-$HOME/.config}/std/estate.toml"
  [[ -f $f && -r $f ]] || return 0            # -f matters: -r alone is TRUE for a directory
  local -a out
  local line k v p n t key
  p=''; n=''
  while IFS= read -r line || [[ -n $line ]]; do
    if [[ $line == (#s)[[:space:]]#\\[* ]]; then     # any [table] / [[array]] header ends the entry
      if [[ $what == repos ]]; then
        key=\${n:-\${p:t}}
        [[ -n $key ]] && out+=($key)
      fi
      p=''; n=''
      continue
    fi
    [[ $line == *=* ]] || continue
    k=\${line%%=*}; k=\${k//[[:space:]]##/}
    v=\${line#*=}
    v=\${v##[[:space:]]##}
    v=\${v%%[[:space:]]##}
    case $k in
      path) p=\${\${v#[\\"\\']}%%[\\"\\']*} ;;
      name) n=\${\${v#[\\"\\']}%%[\\"\\']*} ;;
      tools)
        [[ $what == tools ]] || continue
        v=\${v#*\\[}; v=\${v%%\\]*}
        for t in \${(s:,:)v}; do
          t=\${t//[[:space:]]##/}
          t=\${\${t#[\\"\\']}%%[\\"\\']*}
          [[ -n $t ]] && out+=($t)
        done
        ;;
    esac
  done < $f
  if [[ $what == repos ]]; then                      # flush the final entry (no trailing header)
    key=\${n:-\${p:t}}
    [[ -n $key ]] && out+=($key)
  fi
  print -l -- \${(ou)out}
  return 0
}
_std_estate_repos() { local -a n; n=(\${(f)"$(_std_estate_values repos)"}); (( $#n )) && compadd "$@" -a n; return 0 }
_std_estate_tools() { local -a n; n=(\${(f)"$(_std_estate_values tools)"}${toolWords}); n=(\${(u)n}); compadd "$@" -a n; return 0 }
_std_list() {
  # _arguments invokes a non-space action as: <action[1]> "$subopts[@]" "$expl[@]" <action[2,-1]>
  # (zsh 5.9 /usr/share/zsh/5.9/functions/_arguments:465). So the per-item completer is the LAST
  # argument and EVERYTHING BEFORE IT is compadd options that must be forwarded, not dropped.
  local fn=\${@[-1]}
  local -a opts=("\${@[1,-2]}")
  # _sequence handles the comma list (it zparseopts-strips those options itself and re-passes them
  # to the per-item function); fall back to one value without it.
  if (( $+functions[_sequence] )); then _sequence "\${opts[@]}" -s , $fn; else $fn "\${opts[@]}"; fi
}`;
}

/** Sorted by NAME — never by the rendered spec, under which the repeatable `*--set` sorts first. */
function byName<T extends { readonly name: string }>(xs: readonly T[]): T[] {
  return [...xs].sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
}

/**
 * Generate the `_std` zsh completion from the command surface (3.1's single source). Deterministic and
 * sorted by name at every level, so regeneration is byte-identical (GIT-SoT). Enum VALUES keep their
 * declaration order, so `--format` offers its default (`esm`) first.
 *
 * The `commands: readonly string[]` parameter is gone rather than widened to a union: a union keeps the
 * flat branch alive, and the flat branch is D-b.
 *
 * ⚠ `*::` and not `*:` — with two colons `man zshcompsys` re-scopes `words`/`CURRENT` to "only the
 * normal arguments", which is what makes `$words[1]` the command inside `args)` and the subcommand
 * inside `subargs)`. A single colon leaves `words` global, the nested `case` matches `std`, and the
 * completer silently offers nothing.
 */
export function generateStdCompletion(surface: CommandSurface): string {
  const out: string[] = [
    "#compdef std",
    "# _std — GENERATED by `std alias --install` from the std-cli command surface (AD-7). Do NOT hand-edit.",
    // AFTER the banner and BEFORE `_std()` — the banner is an oracle 3.2 pins byte-for-byte, and the
    // readers must be defined before the completer that names them in an action.
    estateReaderBlock(surface),
    "_std() {",
    '  local curcontext="$curcontext" state line',
    "  typeset -A opt_args",
    "  _arguments -C '1: :->cmd' '*:: :->args' && return 0",
    "  case $state in",
    "    cmd)",
    "      local -a cmds",
    "      cmds=(",
  ];
  const commands = byName(surface.commands);
  for (const cmd of commands) out.push(`        ${describeEntry(cmd.name, cmd.desc)}`);
  out.push("      )", "      _describe -t commands 'std command' cmds", "      ;;");
  out.push("    args)", "      case $words[1] in");

  for (const cmd of commands) {
    out.push(`        ${cmd.name})`);
    if (cmd.subcommands.length === 0) {
      // The flags-only shape (`alias`): its flags complete directly under `args`, with no nested state
      // machine. An emitter that assumed every command has subcommands would emit a `sub)` branch here
      // whose `_describe` array is empty — not a syntax error, so `zsh -n` would pass it.
      const flags = byName(cmd.flags ?? []);
      if (flags.length > 0) {
        out.push(`          _arguments ${flags.map((f) => argSpec(f)).join(" ")}`);
      }
      out.push("          ;;");
      continue;
    }
    out.push("          _arguments -C '1: :->sub' '*:: :->subargs' && return 0");
    out.push("          case $state in", "            sub)", "              local -a subs", "              subs=(");
    const subs = byName(cmd.subcommands);
    for (const sub of subs) out.push(`                ${describeEntry(sub.name, sub.desc)}`);
    out.push(
      "              )",
      `              _describe -t commands 'std ${cmd.name} subcommand' subs`,
      "              ;;",
      "            subargs)",
      "              case $words[1] in",
    );
    for (const sub of subs) {
      const flags = byName(sub.flags);
      if (flags.length === 0) continue;
      const specs = flags.map((f) => argSpec(f, flagEnum(surface, cmd.name, sub.name, f.name)));
      out.push(`                ${sub.name})`, `                  _arguments ${specs.join(" ")}`, "                  ;;");
    }
    out.push("              esac", "              ;;", "          esac", "          ;;");
  }

  out.push("      esac", "      ;;", "  esac", "}", '_std "$@"', "");
  return out.join("\n");
}

/** Where `--install` deploys (all injected — no consumer path baked into std, D4). */
export interface InstallTargets {
  repoNavPath: string; // e.g. ~/.config/zsh/functions/repo-nav.zsh
  completionPath: string; // e.g. ~/.config/zsh/completions/_std
}

/** Inputs for an install run — everything the generator needs, supplied by the caller (identity-free). */
export interface InstallOptions {
  config: RepoConfig;
  /** The command surface the completion is generated from. RENAMED from `commands: readonly string[]`
   *  (3.2) rather than retyped, so every stale callsite is a named compile error, not a type error a
   *  cast could paper over. */
  surface: CommandSurface;
  targets: InstallTargets;
  frozenNames?: ReadonlySet<string>;
}

/** The artifacts an install produced (paths written) — returned for reporting/testing. */
export interface InstallResult {
  repoNavPath: string;
  completionPath: string;
}

/**
 * Generate both artifacts and write them to their deploy targets (creating parent dirs). Fail-loud
 * validation happens first via the generators, so a bad registry writes NOTHING. The targets are
 * one-way deploy outputs (GIT-SoT) — never a second source.
 */
export function installAlias(opts: InstallOptions): InstallResult {
  // Generate BOTH artifacts first — generation fail-closes on a bad registry, so a validation failure
  // writes nothing. Each file is then written via the shared `fsx.atomicWrite` (ensureDir → temp →
  // rename), so a write that fails mid-way never leaves a half-written artifact in the live shell tree.
  const repoNav = generateRepoNav(opts.config, opts.frozenNames ?? new Set());
  const completion = generateStdCompletion(opts.surface);
  for (const [path, content] of [
    [opts.targets.repoNavPath, repoNav],
    [opts.targets.completionPath, completion],
  ] as const) {
    atomicWrite(path, content);
  }
  return { repoNavPath: opts.targets.repoNavPath, completionPath: opts.targets.completionPath };
}

/** Default deploy targets under a ZDOTDIR root (the live `~/.config/zsh`, supplied by the caller). */
export function defaultTargets(zdotdir: string): InstallTargets {
  return {
    repoNavPath: join(zdotdir, "functions", "repo-nav.zsh"),
    completionPath: join(zdotdir, "completions", "_std"),
  };
}

/** Everything the `alias` command needs, resolved by the entrypoint (identity-free — injected for tests). */
export interface AliasDeps {
  config: RepoConfig;
  /** See {@link InstallOptions.surface} — renamed from `commands` for the same reason. */
  surface: CommandSurface;
  targets: InstallTargets;
  frozenNames?: ReadonlySet<string>;
  /** Sink for human output (defaults to console.log); injected so tests can capture it. */
  log?: (line: string) => void;
}

/**
 * The std-cli `alias` command. `--install` generates + deploys repo-nav and the `_std` completion;
 * without it, prints usage. Returns a process exit code (0 ok, 1 fail-loud, 2 usage). Pure dispatch on
 * the flag — the generation/IO lives in `installAlias`, which fail-closes before writing anything.
 */
export function runAlias(argv: string[], deps: AliasDeps): number {
  const log = deps.log ?? ((l: string) => console.log(l));
  if (!argv.includes("--install")) {
    log(renderAliasUsage(deps.surface)); // R-3: rendered from the model, not hand-written here (AC9)
    return 2;
  }
  try {
    const res = installAlias({
      config: deps.config,
      surface: deps.surface,
      targets: deps.targets,
      frozenNames: deps.frozenNames,
    });
    log(`✓ deployed repo-nav → ${res.repoNavPath}`);
    log(`✓ deployed _std completion → ${res.completionPath}`);
    return 0;
  } catch (e) {
    if (e instanceof RepoNavError) {
      console.error(`✗ ${e.message}`);
      return 1;
    }
    throw e; // unexpected — fail loud (NFR3/FR5), never swallow
  }
}
