// Story 4.5 — the AD-7 repo-nav generator + `_std` completion + `alias --install`.
//
// ONE source, TWO outputs (AD-7): `~/.config/std/repos.ts` (the user's registry) is the single source
// of truth; the generated `repo-nav.zsh` and `_std` completion are DEPLOY ARTIFACTS — one-way output,
// never hand-edited (GIT-SoT). Edit the source, regenerate, deploy.
//
// Identity-free (D4/NFR3): std bakes in NO consumer data. The registry entries, the reserved CLI names
// (e.g. the consumer's own command names), and the frozen-name set are all PASSED IN — std owns the
// generator + the schema, the user owns the data, the consumer (zsh-planning) owns the grammar oracle.
//
// Bun edge — fs/os/path are fine here; core stays pure.

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

/** The registry: a map of nav alias → target path (the path string is emitted verbatim into zsh, so a
 *  consumer may use `$HOME`/`~` and zsh expands it at source time). */
export type RepoRegistry = Record<string, string>;

/** The user's `~/.config/std/repos.ts` contract. `reserved` names are CLI commands that must never be
 *  shadowed by a generated cd-alias (reachable via `repo <name>` instead). */
export interface RepoConfig {
  entries: RepoRegistry;
  reserved?: string[];
}

/** zshstd's callable-name grammar (mirrors `fn-names.zsh`: a name matches this, public = not `_`-led).
 *  A generated nav name must conform — the generator fails loud otherwise (AD-7). */
export const NAV_NAME_GRAMMAR = /^[A-Za-z0-9_:.-]+$/;

/** Raised on a grammar violation or a frozen-name collision — the AD-7 fail-loud guards. */
export class RepoNavError extends Error {}

/** The generator's OWN public/private function names — it owns this namespace (these are the artifact,
 *  not cd-aliases), so they are exempt from the cd-alias frozen-collision check. */
const OWNED_NAMES = ["repo", "repos", "_repo"] as const;

/**
 * Validate the registry against the grammar + the injected frozen set, fail-LOUD (AD-7):
 *   - every alias must match `NAV_NAME_GRAMMAR` (else a grammar violation);
 *   - no alias may collide with a frozen callable name (else it would shadow it).
 * Returns the cd-alias keys to emit (sorted, reserved excluded), or throws `RepoNavError`.
 */
export function validateRegistry(
  config: RepoConfig,
  frozenNames: ReadonlySet<string> = new Set(),
): string[] {
  const reserved = new Set(config.reserved ?? []);
  const keys = Object.keys(config.entries).sort();
  for (const key of keys) {
    if (!NAV_NAME_GRAMMAR.test(key)) {
      throw new RepoNavError(
        `repo-nav: alias '${key}' violates the naming grammar ${NAV_NAME_GRAMMAR} (AD-7)`,
      );
    }
    if ((OWNED_NAMES as readonly string[]).includes(key)) {
      throw new RepoNavError(
        `repo-nav: alias '${key}' is reserved by the generator (it defines ${OWNED_NAMES.join("/")}) — ` +
          `choose another alias`,
      );
    }
    // A reserved CLI name is reachable via `repo <name>`, never a cd-alias — so it never shadows, and is
    // not checked for collision. Every OTHER alias must not collide with a frozen callable name.
    if (!reserved.has(key) && frozenNames.has(key)) {
      throw new RepoNavError(
        `repo-nav: alias '${key}' collides with a frozen callable name — generated names must never ` +
          `shadow the frozen set (AD-7). Rename the entry or reserve it.`,
      );
    }
  }
  return keys.filter((k) => !reserved.has(k));
}

const GENERATED_BANNER =
  "# repo-nav.zsh — GENERATED by `std alias --install` from ~/.config/std/repos.ts (AD-7).\n" +
  "# ONE source, TWO outputs. Do NOT hand-edit — edit repos.ts and regenerate. Generated artifacts\n" +
  "# are never frozen (the name surface lives in the source registry).";

// The static behavior (repo/repos/_repo + cd-alias block) is constant — only ZSH_REPOS is data-driven.
const REPO_NAV_BODY = `
# repo <alias> — cd to a registered repo (never shadows a command; tab-completes)
repo() {
  emulate -L zsh
  local key="$1"
  if [[ -z "$key" || -z "\${ZSH_REPOS[$key]}" ]]; then
    print -u2 "repo: unknown '\${key:-}'. Known: \${(ok)ZSH_REPOS}"; return 1
  fi
  cd "\${ZSH_REPOS[$key]}"
}

# repos — list the registry (alias → path)
repos() {
  emulate -L zsh
  local k
  for k in \${(ok)ZSH_REPOS}; do printf '  %-7s %s\\n' "$k" "\${ZSH_REPOS[$k]}"; done
}

# tab-completion for \`repo\`
_repo() { local -a k; k=(\${(ok)ZSH_REPOS}); compadd -a k }
compdef _repo repo 2>/dev/null

# Direct cd-aliases — generated from the registry, but NEVER shadow a real command.
() {
  emulate -L zsh
  local k; local -a reserved=(RESERVED_NAMES)
  for k in \${(k)ZSH_REPOS}; do
    (( \${reserved[(I)$k]} )) && continue                 # reserved CLI name → skip
    command -v "$k" >/dev/null 2>&1 && continue          # a real command owns it → skip
    alias "$k"="cd \${(q)ZSH_REPOS[$k]}"
  done
}
`;

/**
 * Generate the `repo-nav.zsh` artifact from the registry. DETERMINISTIC — entries are emitted in sorted
 * key order so regeneration is byte-identical (GIT-SoT reproducibility). Validates first (fail-loud).
 */
export function generateRepoNav(
  config: RepoConfig,
  frozenNames: ReadonlySet<string> = new Set(),
): string {
  validateRegistry(config, frozenNames);
  const reserved = config.reserved ?? [];
  const keys = Object.keys(config.entries).sort();
  const width = keys.reduce((w, k) => Math.max(w, k.length), 0);
  const rows = keys.map((k) => `  ${k.padEnd(width)}  "${config.entries[k]}"`).join("\n");
  const body = REPO_NAV_BODY.replace("RESERVED_NAMES", reserved.slice().sort().join(" "));
  return `${GENERATED_BANNER}\n\ntypeset -gA ZSH_REPOS=(\n${rows}\n)\n${body}`;
}

/**
 * Generate the `_std` zsh completion from the std-cli command surface (the manifest command names + any
 * std built-ins like `alias`). Deterministic (sorted). One source (the command list) → one output.
 */
export function generateStdCompletion(commands: readonly string[]): string {
  const names = [...new Set(commands)].sort();
  const list = names.map((c) => `    '${c}'`).join(" \\\n");
  return (
    "#compdef std\n" +
    "# _std — GENERATED by `std alias --install` from the std-cli command surface (AD-7). Do NOT hand-edit.\n" +
    "_std() {\n" +
    "  local -a cmds\n" +
    "  cmds=(\\\n" +
    `${list}\n` +
    "  )\n" +
    "  _describe 'std command' cmds\n" +
    "}\n" +
    "_std \"$@\"\n"
  );
}

/** Where `--install` deploys (all injected — no consumer path baked into std, D4). */
export interface InstallTargets {
  repoNavPath: string; // e.g. ~/.config/zsh/functions/repo-nav.zsh
  completionPath: string; // e.g. ~/.config/zsh/completions/_std
}

/** Inputs for an install run — everything the generator needs, supplied by the caller (identity-free). */
export interface InstallOptions {
  config: RepoConfig;
  commands: readonly string[];
  targets: InstallTargets;
  frozenNames?: ReadonlySet<string>;
}

/** The artifacts an install produced (paths written) — returned for reporting/testing. */
export interface InstallResult {
  repoNavPath: string;
  completionPath: string;
}

/**
 * Generate both artifacts and write them to their deploy targets (creating parent dirs). Fail-loud
 * validation happens first via the generators, so a bad registry writes NOTHING. The targets are
 * one-way deploy outputs (GIT-SoT) — never a second source.
 */
export function installAlias(opts: InstallOptions): InstallResult {
  const repoNav = generateRepoNav(opts.config, opts.frozenNames ?? new Set());
  const completion = generateStdCompletion(opts.commands);
  for (const [path, content] of [
    [opts.targets.repoNavPath, repoNav],
    [opts.targets.completionPath, completion],
  ] as const) {
    const dir = dirname(path);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(path, content);
  }
  return { repoNavPath: opts.targets.repoNavPath, completionPath: opts.targets.completionPath };
}

/** Default deploy targets under a ZDOTDIR root (the live `~/.config/zsh`, supplied by the caller). */
export function defaultTargets(zdotdir: string): InstallTargets {
  return {
    repoNavPath: join(zdotdir, "functions", "repo-nav.zsh"),
    completionPath: join(zdotdir, "completions", "_std"),
  };
}

/** Everything the `alias` command needs, resolved by the entrypoint (identity-free — injected for tests). */
export interface AliasDeps {
  config: RepoConfig;
  commands: readonly string[];
  targets: InstallTargets;
  frozenNames?: ReadonlySet<string>;
  /** Sink for human output (defaults to console.log); injected so tests can capture it. */
  log?: (line: string) => void;
}

/**
 * The std-cli `alias` command. `--install` generates + deploys repo-nav and the `_std` completion;
 * without it, prints usage. Returns a process exit code (0 ok, 1 fail-loud, 2 usage). Pure dispatch on
 * the flag — the generation/IO lives in `installAlias`, which fail-closes before writing anything.
 */
export function runAlias(argv: string[], deps: AliasDeps): number {
  const log = deps.log ?? ((l: string) => console.log(l));
  if (!argv.includes("--install")) {
    log("usage: std alias --install   # (re)generate repo-nav + _std completion from ~/.config/std/repos.ts");
    return 2;
  }
  try {
    const res = installAlias({
      config: deps.config,
      commands: deps.commands,
      targets: deps.targets,
      frozenNames: deps.frozenNames,
    });
    log(`✓ deployed repo-nav → ${res.repoNavPath}`);
    log(`✓ deployed _std completion → ${res.completionPath}`);
    return 0;
  } catch (e) {
    if (e instanceof RepoNavError) {
      console.error(`✗ ${e.message}`);
      return 1;
    }
    throw e; // unexpected — fail loud (NFR3/FR5), never swallow
  }
}
