import { describe, expect, test } from "bun:test";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { spawnCapture } from "../proc";
import {
  NAV_NAME_GRAMMAR,
  RepoNavError,
  SURFACE,
  defaultTargets,
  generateRepoNav,
  generateStdCompletion,
  installAlias,
  runAlias,
  validateRegistry,
  type RepoConfig,
} from "./index";
// `describeEntry`/`argSpec` are repo-nav exports, NOT barrel exports: AC7 fences `index.ts` to exactly
// two new re-exports (`SURFACE` + `CommandSurface`), so the escaping helpers are imported directly.
import { argSpec, describeEntry } from "./repo-nav";

const cfg: RepoConfig = {
  entries: { zp: "$HOME/Dev/zsh-planning", mph: "$HOME/Sites/melb-print-hub", std: "$HOME/Dev/std" },
  reserved: ["std"],
};

describe("validateRegistry — fail-loud guards (AC2)", () => {
  test("accepts a clean registry and returns sorted, reserved-excluded cd-alias keys", () => {
    expect(validateRegistry(cfg)).toEqual(["mph", "zp"]); // sorted; 'std' reserved → excluded
  });

  test("fail-loud on a grammar violation, naming the offender", () => {
    const bad: RepoConfig = { entries: { "bad name": "/x" } };
    expect(() => validateRegistry(bad)).toThrow(RepoNavError);
    expect(() => validateRegistry(bad)).toThrow(/'bad name' violates the naming grammar/);
  });

  test("fail-loud on a leading-underscore alias (nav aliases are public)", () => {
    expect(() => validateRegistry({ entries: { _hidden: "/x" } })).toThrow(/starts with '_'/);
  });

  test("fail-loud on an alias colliding with the generator's own repo/repos", () => {
    expect(() => validateRegistry({ entries: { repo: "/x" } })).toThrow(/reserved by the generator/);
  });

  test("fail-loud on a frozen-name collision", () => {
    const frozen = new Set(["forge", "agent"]);
    const collide: RepoConfig = { entries: { forge: "/x", zp: "/y" } };
    expect(() => validateRegistry(collide, frozen)).toThrow(/'forge' collides with a frozen callable/);
  });

  test("a reserved alias is NOT checked for frozen collision (reachable via `repo <name>`)", () => {
    const frozen = new Set(["std"]);
    expect(() => validateRegistry(cfg, frozen)).not.toThrow(); // 'std' is reserved → skipped
  });

  test("the grammar matches zshstd callable names and rejects spaces/empties", () => {
    expect(NAV_NAME_GRAMMAR.test("gh-pr-view")).toBe(true);
    expect(NAV_NAME_GRAMMAR.test("nlm_zsh")).toBe(true);
    expect(NAV_NAME_GRAMMAR.test("a b")).toBe(false);
    expect(NAV_NAME_GRAMMAR.test("")).toBe(false);
  });
});

describe("generateRepoNav — deterministic, declaration-ordered, complete (AC1)", () => {
  const out = generateRepoNav(cfg);

  test("is byte-identical on regeneration (GIT-SoT reproducibility)", () => {
    expect(generateRepoNav(cfg)).toBe(out);
  });

  test("emits entries in repos.ts declaration order (preserves the user's priority)", () => {
    const block = out.slice(out.indexOf("ZSH_REPOS=("), out.indexOf(")", out.indexOf("ZSH_REPOS=(")));
    const keys = block
      .split("\n")
      .map((l) => l.match(/^\s+(\S+)\s+"/)?.[1])
      .filter((k): k is string => Boolean(k));
    expect(keys).toEqual(["zp", "mph", "std"]); // declaration order, NOT sorted
  });

  test("carries the generated banner + ZSH_REPOS + repo/repos functions", () => {
    expect(out).toContain("GENERATED by `std alias --install`");
    expect(out).toContain("typeset -gA ZSH_REPOS=(");
    expect(out).toContain("repo() {");
    expect(out).toContain("repos() {");
    expect(out).toContain("compdef _repo repo");
  });

  test("injects the reserved names into the cd-alias skip-list (no hardcoded consumer names)", () => {
    expect(out).toContain("local -a reserved=(std)");
  });

  test("repos() lists 3 columns — derived name, colorized TTY-only, $HOME-shortened path", () => {
    expect(out).toContain("${ZSH_REPOS[$k]:t}"); // name = path basename (derived, no registry field)
    expect(out).toContain("[[ -t 1 && -z ${NO_COLOR:-} ]]"); // color gate: plain when piped/headless
    expect(out).toContain("\\e[36m"); // cyan on the name column only
    expect(out).toContain('disp="${ZSH_REPOS[$k]/#$HOME/~}"'); // $HOME → ~; QUOTED (else zsh re-expands ~)
    expect(out).toContain("printf '  %-7s %s%-*s%s  %s\\n'"); // 3 fields, dynamically aligned
  });

  test("a bad registry throws before producing any output (fail-closed)", () => {
    expect(() => generateRepoNav({ entries: { "x y": "/z" } })).toThrow(RepoNavError);
  });
});

// ── the `_std` completion: emitter + the two zsh probes that make its absences real (3.2) ──────────
//
// `zsh` is probed at MODULE SCOPE because `test.skipIf` is evaluated at registration time and cannot
// read an exit code produced inside a test body. `spawnCapture` resolves `127` on a launch failure and
// never rejects, so a box without zsh SKIPS (exit 0) rather than failing the run. Precedent: `HAS_COMM`
// in `src/bmad/bmad-verify.test.ts`.
const HAS_ZSH = (await spawnCapture("zsh", ["-c", "exit 0"])).code !== 127;

// Both probes are held as string constants and written into the same temp dir as the artifact — NEVER
// committed as a `src/cli/*.zsh` fixture. Every gate globs `.ts` (`src/**/*.ts`, and narrower still
// `src/core/**/*.ts`), so a `.zsh` file under `src/` would be an executable script inside the library
// tree that no gate owns. Avoidable for free.
//
// The stubs return 1 while descending and 0 (flags) / 1 (names) on arrival — that is what makes the
// emitter's real `&& return 0` behave under the stub as it does under real zsh. `${@:#-C}` drops the
// `-C` flag so it is not mistaken for a spec. A `zpty`-driven real-completion harness was tried and
// rejected upstream: PTY echo and `compinit` noise make it flaky, for the same assertion.
const PROBE_FLAGS = `#!/bin/zsh -f
emulate -L zsh
local -a TARGET; TARGET=(\${=2})
local -a CAPTURED
integer depth=0
_arguments() {
  local -a specs; specs=("\${@:#-C}")
  (( depth++ ))
  if (( depth <= $#TARGET )); then
    state=\${specs[-1]##*->}
    words=(\${TARGET[depth,-1]})
    return 1
  fi
  CAPTURED+=("\${specs[@]}"); return 0
}
_describe() { CAPTURED+=("\${@[3,-1]}"); return 0 }
compadd() { return 0 }; _files() { return 0 }
source $1 >/dev/null 2>&1
CAPTURED=(); depth=0
words=(\${TARGET}); CURRENT=$(( $#TARGET + 1 )); local state= line=
_std
print -l -- $CAPTURED
`;

// Three deltas from PROBE_FLAGS, all load-bearing: descend to `$#TARGET + 1` rather than `$#TARGET`;
// take the state from `specs[1]` (the `1:` NAME state) rather than `specs[-1]` (the `*::` descend
// state); and dereference the array `_describe` is handed with `${(@P)…}` — plain `${(P)…}` joins every
// row into one word and yields a plausible-looking one-element result. `probeFlags` CANNOT read names:
// at its leaf the `_arguments` stub returns 0, so the emitter's `&& return 0` short-circuits before the
// `case $state in cmd|sub)` branch runs, leaving its own `_describe` stub unreachable.
const PROBE_NAMES = `#!/bin/zsh -f
emulate -L zsh
local -a TARGET; TARGET=(\${=2})
local -a CAPTURED
integer depth=0
integer LIMIT=$(( $#TARGET + 1 ))
_arguments() {
  local -a specs; specs=("\${@:#-C}")
  (( depth++ ))
  if (( depth < LIMIT )); then
    state=\${specs[-1]##*->}
    words=(\${TARGET[depth,-1]})
    return 1
  fi
  state=\${specs[1]##*->}
  return 1
}
_describe() { CAPTURED+=("\${(@P)\${@[-1]}}"); return 0 }
compadd() { return 0 }; _files() { return 0 }
source $1 >/dev/null 2>&1
CAPTURED=(); depth=0
words=(\${TARGET}); CURRENT=$(( $#TARGET + 1 )); local state= line=
_std
print -l -- $CAPTURED
`;

/** Run one probe over `artifact`, walking `path` (e.g. `"bmad deploy"`; `""` = top level). */
async function runProbe(script: string, artifact: string, path: string): Promise<string[]> {
  const root = mkdtempSync(join(tmpdir(), "std-probe-"));
  try {
    const scriptPath = join(root, "probe.zsh");
    const artifactPath = join(root, "_std");
    writeFileSync(scriptPath, script);
    writeFileSync(artifactPath, artifact);
    const r = await spawnCapture("zsh", [scriptPath, artifactPath, path]);
    return r.stdout.split("\n").filter(Boolean);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
}

/** The flag names `_arguments` is actually handed at the end of `path`, in emitted order. */
async function probeFlags(artifact: string, path: string): Promise<string[]> {
  const rows = await runProbe(PROBE_FLAGS, artifact, path);
  return rows.map((l) => l.replace(/\[.*$/, "")).filter((l) => l.includes("--"));
}

/** The child names `_describe` is actually handed at `path` (`""` = the top-level commands). */
async function probeNames(artifact: string, path: string): Promise<string[]> {
  const rows = await runProbe(PROBE_NAMES, artifact, path);
  return rows.map((l) => l.split(":")[0]!);
}

/**
 * The FULL optspecs at `path`, tails included (3.3).
 *
 * The SAME zsh harness as `probeFlags` — the difference is TS-side only, and it is the whole point:
 * `probeFlags` cuts every row at its first `[`, so no 3.2 assertion can see a `:message:action` tail at
 * all. A whole-artifact `expect(out).toContain(…)` is not a substitute: it matches the reader's own body,
 * a comment, anything.
 */
async function probeSpecs(artifact: string, path: string): Promise<string[]> {
  const rows = await runProbe(PROBE_FLAGS, artifact, path);
  return rows.filter((l) => l.includes("--"));
}

/** The spec for one flag out of a `probeSpecs` result. `undefined` when the flag is not offered there. */
function specOf(specs: string[], flag: string): string | undefined {
  return specs.find((s) => s.startsWith(flag));
}

// ── the estate-reader probe: the AC4/AC5/AC7 mechanism (3.3) ───────────────────────────────────────
//
// The emitted readers are drivable without a PTY: source the artifact under `zsh -f` with the completion
// system stubbed, point `XDG_CONFIG_HOME` at a fixture dir, and call the action the way `_arguments`
// does. Four traps, all of them live:
//   1. `source`ing a `#compdef` file EXECUTES its trailing `_std "$@"` — reset `CAPTURED` after it.
//   2. `compadd -a n` passes the array NAME, not its elements. `${(@P)…}` dereferences; plain `${(P)…}`
//      joins every element into one word and yields a one-element result that still looks plausible.
//   3. `${=3}` (word-split), not `$3` — else `_std_list _std_estate_repos` is looked up as one command.
//   4. 🔴 The `-J`/`-X` injection is LOAD-BEARING. `_arguments` dispatches a non-space action as
//      `"$action[1]" "$subopts[@]" "$expl[@]" "${(@)action[2,-1]}"` (zsh 5.9 `_arguments:465`) and
//      `expl` is never empty — every branch of `_description`'s `set -A` ends in at least `-J <group>`.
//      A harness that word-splits and calls, and stops there, hands `_std_list` exactly the argv a naive
//      `$1`-reading wrapper expects, and passes over the broken form. With the injection, `$1` is `-J`
//      and the wrapper returns nothing. Drive `_std_list <fn>` (the action AS EMITTED), never the leaf
//      bare — driving the leaf directly bypasses the wrapper and re-blinds the harness.
const PROBE_READER = `#!/bin/zsh -f
emulate -L zsh
local -a CAPTURED
_arguments() { return 0 }; _describe() { return 0 }; _files() { return 0 }
compadd() { if [[ \${@[-2]} == -a ]]; then CAPTURED+=("\${(@P)@[-1]}"); else CAPTURED+=("$@"); fi; return 0 }
source $1 >/dev/null 2>&1
CAPTURED=()
export XDG_CONFIG_HOME=$2
local -a words=(\${=3})
if (( $#words > 1 )); then $words[1] -J probe-group -X probe-descr "\${(@)words[2,-1]}"; else \${=3}; fi
print -l -- $CAPTURED
`;

interface ReaderResult {
  /** The words `compadd` was handed. */
  values: string[];
  code: number;
  /** Asserted EMPTY by every degradation row — a completer that writes to stderr prints over the prompt. */
  stderr: string;
}

/** Drive `action` (e.g. `"_std_list _std_estate_repos"`) against the estate under `xdg`. */
async function probeReader(artifact: string, xdg: string, action: string): Promise<ReaderResult> {
  const root = mkdtempSync(join(tmpdir(), "std-reader-"));
  try {
    const scriptPath = join(root, "probe.zsh");
    const artifactPath = join(root, "_std");
    writeFileSync(scriptPath, PROBE_READER);
    writeFileSync(artifactPath, artifact);
    const r = await spawnCapture("zsh", [scriptPath, artifactPath, xdg, action]);
    return { values: r.stdout.split("\n").filter(Boolean), code: r.code, stderr: r.stderr };
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
}

/** Write `toml` to `<dir>/std/estate.toml` and return `dir` (the `XDG_CONFIG_HOME` the reader reads). */
function estateDir(toml: string): string {
  const dir = mkdtempSync(join(tmpdir(), "std-estate-"));
  mkdirSync(join(dir, "std"), { recursive: true });
  writeFileSync(join(dir, "std", "estate.toml"), toml);
  return dir;
}

/**
 * The AC4 fixture. Four entries, each earning its place: an implicit key from `basename`, a declared
 * `tools` array, a `#` inside a string value (which is NOT a comment), and an explicit `name` on a
 * `source-only` entry — the one shape reachable only by naming it.
 */
const FIXTURE = `[[repos]]
path = "~/Dev/example-repo"
claudeTracked = true
hasUpstream = true

[[repos]]
path = "~/Dev/example-workspace/another-repo"
claudeTracked = true
hasUpstream = false
branch = "feature/some-work"
tools = ["claude-code"]

[[repos]]
path = "~/Dev/example-workspace/gitignored-repo"
claudeTracked = false
hasUpstream = true
notes = "working-copy-only; # not a comment"

[[repos]]
path = "~/example-hq/packs/example-pack"
name = "example-pack"
role = "source-only"
claudeTracked = false
hasUpstream = false
tools = ["claude-code", "some-other-tool"]
`;

describe("generateStdCompletion — the two-level emitter, derived from the surface (AC1/AC5)", () => {
  const out = generateStdCompletion(SURFACE);

  test("byte-identical on regeneration (GIT-SoT), and the banner is preserved exactly", () => {
    expect(generateStdCompletion(SURFACE)).toBe(out);
    expect(out.split("\n")[0]).toBe("#compdef std");
    expect(out).toContain(
      "# _std — GENERATED by `std alias --install` from the std-cli command surface (AD-7). Do NOT hand-edit.",
    );
  });

  test("emits the two-level `_arguments -C` state machine, both structural shapes", () => {
    expect(out).toContain("_arguments -C '1: :->cmd' '*:: :->args' && return 0");
    expect(out).toContain("_arguments -C '1: :->sub' '*:: :->subargs' && return 0");
    // `alias` has flags and NO subcommands: its `--install` completes directly under `args`, with no
    // nested state machine. An emitter that assumed every command has subs would emit an empty `sub)`
    // branch here — not a syntax error, so `zsh -n` would pass it. AC2's `alias` probe is the gate.
    expect(out).toContain("_arguments '--install[");
  });

  test("names and flag specs are sorted BY NAME at every level; enum values keep declaration order", () => {
    expect(out.indexOf("'alias:")).toBeLessThan(out.indexOf("'bmad:"));
    expect(out.indexOf("'bmad:")).toBeLessThan(out.indexOf("'cn:"));
    expect(out.indexOf("'cn:")).toBeLessThan(out.indexOf("'dashkit:"));
    // Sorted on the flag NAME, never on the rendered spec: `*--set` renders with a leading `*`, which
    // sorts BEFORE `-`, so `[...specs].sort()` would hoist it to the front. Nothing else catches this —
    // neither exact-set assertion below carries a repeatable flag.
    const deploy = out.slice(out.indexOf("                deploy)\n                  _arguments '--apply"));
    const line = deploy.split("\n")[1]!;
    expect(line.indexOf("'--push[")).toBeLessThan(line.indexOf("'*--set["));
    expect(line.indexOf("'*--set[")).toBeLessThan(line.indexOf("'--skills["));
  });

  // No probe assertion reaches the `:message:action` tail — `probeFlags` cuts every row at its first
  // `[`. A naive emitter ships `:<dir>:_files -/` (the metavar is a DISPLAY string carrying angle
  // brackets, since HELP renders `--vault <dir>`), which `zsh -n` accepts and which shows up only as a
  // wrong prompt at a live `<TAB>`. So it is asserted directly, on the text.
  test("the value tails are derived and angle-stripped", () => {
    expect(out).toContain(":dir:_files -/");
    expect(out).not.toContain(":<dir>:");
    expect(out).toContain(":fmt:(esm cjs)"); // from CN_SPEC.formats, never restated in the emitter
    expect(out).toContain(":a,b:'"); // a `list` flag: empty action — completing it from the estate is 3.3
  });
});

describe("the emitted `_std` under a real zsh (AC2/AC3/AC6/AC7)", () => {
  const out = generateStdCompletion(SURFACE);

  test.skipIf(!HAS_ZSH)("parses — `zsh -n` exits 0", async () => {
    const root = mkdtempSync(join(tmpdir(), "std-zshn-"));
    try {
      const file = join(root, "_std");
      writeFileSync(file, out);
      const r = await spawnCapture("zsh", ["-n", file]);
      expect(r.stderr).toBe("");
      expect(r.code).toBe(0);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  // ABSENCE IS THE BAR — and it is asserted through a real zsh parse, never by string-matching the
  // generated text. `expect(out).not.toContain("--repos")` is worthless here: `--repos` legitimately
  // appears under `install`, `update` and `verify`, so it could only ever be red.
  test.skipIf(!HAS_ZSH)("bmad deploy does NOT offer --repos (BM-19); install DOES", async () => {
    expect(await probeFlags(out, "bmad deploy")).not.toContain("--repos");
    // The anti-tautology control. A harness that silently breaks — wrong stub arity, unsourced file, a
    // `state` never set — returns `[]` for EVERY path, and `[].not.toContain(…)` is green. Without a
    // path asserted to CONTAIN `--repos`, the absence assertion above proves nothing.
    expect(await probeFlags(out, "bmad install")).toContain("--repos");
  });

  test.skipIf(!HAS_ZSH)("bmad verify offers exactly its three; alias offers exactly --install", async () => {
    // `verify --apply` raises no error at all — `cli.ts` parses it for verify too and then never reads
    // it — so offering it is silent nonsense rather than a visible failure. Hence an exact set, here.
    expect(await probeFlags(out, "bmad verify")).toEqual(["--json", "--repos", "--skills"]);
    // Walks the flags-only branch, which is what makes the `alias` shape's assertion non-vacuous.
    expect(await probeFlags(out, "alias")).toEqual(["--install"]);
  });

  test.skipIf(!HAS_ZSH)("dashkit deploy offers NO --format, and IS reachable (AC6)", async () => {
    // DASHKIT_SPEC declares no `formats`, so `edge-deploy` never parses one for dashkit.
    expect(await probeFlags(out, "dashkit deploy")).not.toContain("--format");
    // 🔴 Load-bearing, and the `cn` control below does NOT substitute for it: probing a path the
    // artifact never emits returns `[]`, and `[].not.toContain("--format")` is green — so an emitter
    // that dropped `dashkit` entirely would pass the line above. `dashkit` has no other assertion in
    // this suite, so without a control on ITS OWN path this test is green-on-missing.
    expect(await probeFlags(out, "dashkit deploy")).toContain("--vault");
    expect(await probeFlags(out, "cn deploy")).toContain("--format"); // proves the harness, not dashkit
  });

  // D-a itself: every assertion above is about FLAGS, so an emitter that emitted `alias` and silently
  // dropped `bmad`/`cn`/`dashkit` would pass all of them. The name lists have to be read too.
  test.skipIf(!HAS_ZSH)("every command and subcommand ARRIVED in the _describe arrays (D-a)", async () => {
    expect(await probeNames(out, "")).toEqual(["alias", "bmad", "cn", "dashkit"]);
    expect(await probeNames(out, "bmad")).toEqual(["deploy", "install", "update", "verify"]);
    expect(await probeNames(out, "cn")).toEqual(["deploy", "verify"]);
    expect(await probeNames(out, "dashkit")).toEqual(["deploy", "verify"]);
  });
});

// ── 3.3: value completion for --repos / --tools from the caller-local estate ───────────────────────

describe("the `source` → reader action mapping, read through the TAIL (3.3 AC3/AC9)", () => {
  const out = generateStdCompletion(SURFACE);

  test.skipIf(!HAS_ZSH)("--repos and --tools carry the reader action; the message half is 3.2's", async () => {
    expect(specOf(await probeSpecs(out, "bmad install"), "--repos")).toMatch(
      /:a,b:_std_list _std_estate_repos$/,
    );
    expect(specOf(await probeSpecs(out, "bmad verify"), "--repos")).toMatch(
      /:a,b:_std_list _std_estate_repos$/,
    );
    // 🔴 The control on `deploy`'s OWN path, and it is not redundant with `install`: `deploy` is the one
    // subcommand with no `--repos` (BM-19), so an emitter that dropped `deploy` entirely would leave
    // every `--repos` line above green.
    expect(specOf(await probeSpecs(out, "bmad deploy"), "--tools")).toMatch(
      /:a,b:_std_list _std_estate_tools$/,
    );
  });

  // OUT OF SCOPE, ASSERTED AS AN ABSENCE. `--skills`' vocabulary is the estate MODULE's `skills/` dir
  // (resolved from the installed package, not the caller's estate) and is doubled by the `bmad-agent-`
  // shorthand; `--set`'s `m.k=v` has no enumerable source anywhere. Both go red the day someone wires a
  // reader for them without a story.
  test.skipIf(!HAS_ZSH)("--skills and --set keep the EMPTY action", async () => {
    expect(specOf(await probeSpecs(out, "bmad verify"), "--skills")).toMatch(/:a,b:$/);
    expect(specOf(await probeSpecs(out, "bmad install"), "*--set")).toMatch(/:m\.k=v:$/);
  });

  // The probe's own control: a `probeSpecs` that silently returned rows with no tails would make every
  // `/:a,b:$/` above pass. `--vault` is a tail nothing in this story touches.
  test.skipIf(!HAS_ZSH)("probeSpecs really carries tails — the harness control", async () => {
    expect(specOf(await probeSpecs(out, "cn deploy"), "--vault")).toMatch(/:dir:_files -\/$/);
    expect(specOf(await probeSpecs(out, "cn deploy"), "--format")).toMatch(/:fmt:\(esm cjs\)$/);
  });

  test("the emitted reader forwards compadd options at BOTH links of the chain (AC8)", () => {
    // `_sequence` re-passes `-S ,` and `-F dedup` THROUGH the per-item function. Dropping `"$@"` still
    // returns the right names — so every assertion in this file stays green — and silently loses comma
    // continuation and already-typed suppression at the live `<TAB>`. Only AC13 sees that half.
    expect(out).toContain('compadd "$@" -a n');
    expect(out).not.toMatch(/compadd -a n/);
    // The other link, one level up. This one IS behaviourally covered — see the AC4 rows below.
    expect(out).toMatch(/local fn=\$\{@\[-1\]\}/);
  });

  test("the reader block sits AFTER the banner and BEFORE `_std()` (AC10)", () => {
    expect(out.split("\n")[0]).toBe("#compdef std");
    expect(out.indexOf("_std_estate_values() {")).toBeLessThan(out.indexOf("\n_std() {"));
    expect(out.indexOf("# _std — GENERATED by")).toBeLessThan(out.indexOf("_std_estate_values() {"));
    expect(generateStdCompletion(SURFACE)).toBe(out); // static text ⇒ still deterministic
  });
});

describe("the emitted reader DRIVEN against fixture estates (3.3 AC4/AC6/AC8)", () => {
  const out = generateStdCompletion(SURFACE);

  // 🔴 THE POSITIVE CONTROL for every `toEqual([])` in the degradation block below. A silently broken
  // `probeReader` returns `[]` for every input and makes all nine of those rows pass. These two must be
  // non-empty, in this file, through the same harness.
  test.skipIf(!HAS_ZSH)("--repos returns the estate's names — INCLUDING the source-only entry (AC6)", async () => {
    const dir = estateDir(FIXTURE);
    try {
      const r = await probeReader(out, dir, "_std_list _std_estate_repos");
      // `example-pack` is the `role = "source-only"` entry. `selectRepos` excludes those from the
      // DEFAULT set only — naming one explicitly is the one way to reach it, so a completer that
      // filtered them would make the one shape you can ONLY reach by typing un-typeable.
      expect(r.values).toEqual(["another-repo", "example-pack", "example-repo", "gitignored-repo"]);
      expect(r.code).toBe(0);
      expect(r.stderr).toBe("");
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  test.skipIf(!HAS_ZSH)("--tools unions the declared tools with the model's defaults", async () => {
    const dir = estateDir(FIXTURE);
    try {
      const r = await probeReader(out, dir, "_std_list _std_estate_tools");
      // ⚠ NOT sorted, and the assertion describes what the code does rather than what looks tidy:
      // `${(ou)out}` sorts the FILE-derived names, the defaults are then appended and `${(u)}` dedupes
      // in place — so `claude-code` keeps its earlier position and the two defaults land last.
      expect(r.values).toEqual(["claude-code", "some-other-tool", "antigravity-cli"]);
      expect(r.stderr).toBe("");
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  // A DOCUMENTED CEILING, pinned so it is a stated limitation rather than a later discovery. The reader
  // is a line scanner: widening this means buffering across lines, which is where it turns into a TOML
  // parser. It degrades to FEWER completions and never to an error.
  test.skipIf(!HAS_ZSH)("a multi-line `tools = [ … ]` array drops its tools; the defaults survive", async () => {
    const dir = estateDir(
      '[[repos]]\npath = "~/Dev/multiline-repo"\ntools = [\n  "only-in-multiline",\n]\n',
    );
    try {
      const r = await probeReader(out, dir, "_std_list _std_estate_tools");
      expect(r.values).toEqual(["claude-code", "antigravity-cli"]);
      expect(r.values).not.toContain("only-in-multiline");
      // The control on the SAME fixture: the repo name IS read, so this proves the ceiling rather than
      // a fixture the reader never opened.
      expect((await probeReader(out, dir, "_std_list _std_estate_repos")).values).toEqual([
        "multiline-repo",
      ]);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe("degradation: a bad estate yields NO completions, rc 0, and never errors the shell (3.3 AC5)", () => {
  const out = generateStdCompletion(SURFACE);
  // `chmod 000` is not a fence root can honour — root reads an unreadable file, so the row would report
  // the fixture's names. Skipping under root is the same capability-fence shape as `HAS_ZSH`.
  const IS_ROOT = typeof process.getuid === "function" && process.getuid() === 0;

  /** Build a fixture dir, run the repos reader over it, and clean up. */
  async function repos(build: (dir: string) => void): Promise<ReaderResult> {
    const dir = mkdtempSync(join(tmpdir(), "std-degrade-"));
    try {
      mkdirSync(join(dir, "std"), { recursive: true });
      build(dir);
      return await probeReader(out, dir, "_std_list _std_estate_repos");
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  }

  const file = (dir: string) => join(dir, "std", "estate.toml");

  test.skipIf(!HAS_ZSH)("the estate file is absent", async () => {
    const r = await repos(() => {});
    expect(r.values).toEqual([]);
    expect(r.code).toBe(0);
    // The red-turning input for the `[[ -f $f && -r $f ]]` guard: without it this row emits a
    // `no such file or directory` line, which in a live shell prints over the prompt.
    expect(r.stderr).toBe("");
  });

  // ⚠ THIS ROW IS DEFENSIVE, AND SAYING SO IS THE HONEST LABEL. `[[ -r $f ]]` is TRUE for a readable
  // directory, so the `-f` conjunct is what makes the guard mean what it says — but MEASURED on
  // darwin/zsh 5.9, weakening the guard to a lone `-r` leaves this row GREEN: the `< $dir` redirect
  // fails, and it fails QUIETLY, so there is no observable difference to assert on. The `-f` stays
  // because the guard should not depend on that; this test does not claim to cover it. What DOES have
  // teeth is deleting the guard outright — the `stderr` assertions below turn red on it.
  test.skipIf(!HAS_ZSH)("estate.toml is a DIRECTORY", async () => {
    const r = await repos((dir) => mkdirSync(file(dir)));
    expect(r.values).toEqual([]);
    expect(r.code).toBe(0);
    expect(r.stderr).toBe("");
  });

  test.skipIf(!HAS_ZSH)("estate.toml is 4 KB of binary noise", async () => {
    const noise = new Uint8Array(4096);
    for (let i = 0; i < noise.length; i++) noise[i] = (i * 7919) % 256;
    const r = await repos((dir) => writeFileSync(file(dir), noise));
    expect(r.values).toEqual([]);
    expect(r.code).toBe(0);
    expect(r.stderr).toBe("");
  });

  test.skipIf(!HAS_ZSH)("it parses but declares no [[repos]]", async () => {
    const r = await repos((dir) => writeFileSync(file(dir), "foo = 1\n"));
    expect(r.values).toEqual([]);
    expect(r.stderr).toBe("");
  });

  test.skipIf(!HAS_ZSH)("the file is empty", async () => {
    const r = await repos((dir) => writeFileSync(file(dir), ""));
    expect(r.values).toEqual([]);
    expect(r.stderr).toBe("");
  });

  test.skipIf(!HAS_ZSH || IS_ROOT)("the file is chmod 000", async () => {
    const r = await repos((dir) => writeFileSync(file(dir), FIXTURE, { mode: 0o000 }));
    expect(r.values).toEqual([]);
    expect(r.code).toBe(0);
    expect(r.stderr).toBe("");
  });

  // The last three rows are NOT `[]`: they are the malformed-looking inputs the reader must still read.
  test.skipIf(!HAS_ZSH)("CRLF line endings — the \\r is stripped", async () => {
    const r = await repos((dir) =>
      writeFileSync(file(dir), '[[repos]]\r\npath = "~/Dev/crlf-repo"\r\n'),
    );
    expect(r.values).toEqual(["crlf-repo"]);
    expect(r.stderr).toBe("");
  });

  // The `|| [[ -n $line ]]` half of the `while read` condition: without it `read` returns non-zero on
  // the unterminated last line and the entry is silently dropped.
  test.skipIf(!HAS_ZSH)("no trailing newline — the last entry survives", async () => {
    const r = await repos((dir) =>
      writeFileSync(file(dir), '[[repos]]\npath = "~/Dev/no-final-newline"'),
    );
    expect(r.values).toEqual(["no-final-newline"]);
    expect(r.stderr).toBe("");
  });

  test.skipIf(!HAS_ZSH)("an entry with neither path nor name is skipped; the others are kept", async () => {
    const r = await repos((dir) =>
      writeFileSync(
        file(dir),
        '[[repos]]\nclaudeTracked = true\n\n[[repos]]\npath = "~/Dev/kept-repo"\n',
      ),
    );
    expect(r.values).toEqual(["kept-repo"]);
    expect(r.stderr).toBe("");
  });

  // 🔴 The one row that distinguishes "the defaults are wired" from "the reader ran": `--tools` does NOT
  // degrade to `[]`. With no estate at all it still offers std's own vocabulary.
  test.skipIf(!HAS_ZSH)("--tools with NO estate file still offers the model's defaults", async () => {
    const dir = mkdtempSync(join(tmpdir(), "std-degrade-"));
    try {
      const r = await probeReader(out, dir, "_std_list _std_estate_tools");
      expect(r.values).toEqual(["claude-code", "antigravity-cli"]);
      expect(r.code).toBe(0);
      expect(r.stderr).toBe("");
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe("std emits the READER, never the names (3.3 AC7 — D4/NFR3)", () => {
  // 🔴 `check:no-consumer-ids` is NOT the assertion that proves this, and presenting it as one is the
  // vacuous-gate shape this epic exists to remove: it is a SIX-NAME denylist, so a real repo name baked
  // into the emitter sails straight through it. Keep that gate green; this is the evidence.
  const PLANTED = ["zzz-planted-repo-a", "zzz-planted-repo-b"];
  const PLANTED_FIXTURE = PLANTED.map((n) => `[[repos]]\npath = "~/Dev/${n}"\n`).join("\n");

  test.skipIf(!HAS_ZSH)("generating with a populated estate IN SCOPE produces an estate-free artifact", async () => {
    const dir = estateDir(PLANTED_FIXTURE);
    const prev = process.env.XDG_CONFIG_HOME;
    let out: string;
    try {
      // The exact path `resolveManifestPath()` reads — so a generator that opened the estate would find
      // this file, not an empty one.
      process.env.XDG_CONFIG_HOME = dir;
      out = generateStdCompletion(SURFACE);
    } finally {
      // `bun test` runs files in ONE process; a leaked env var would follow every later test.
      if (prev === undefined) delete process.env.XDG_CONFIG_HOME;
      else process.env.XDG_CONFIG_HOME = prev;
    }
    try {
      // Half one: the artifact is independent of the estate that was in scope when it was generated.
      // Planted names that cannot occur incidentally — never `example-repo`.
      for (const n of PLANTED) expect(out).not.toContain(n);
      // 🔴 Half two, and BOTH OR NEITHER: the line above is green on an emitter that emits no reader at
      // all. This proves the fixture is real, the path is the one the reader reads, and the values
      // arrive AT COMPLETION TIME rather than at generate time.
      expect((await probeReader(out, dir, "_std_list _std_estate_repos")).values).toEqual(PLANTED);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  // Raised by CodeRabbit on PR #72: `estateDefaults` is generic over `FlagValueSource`, but only
  // `_std_estate_tools` unions its result — `_std_estate_repos` unions none. Today that is invisible
  // because `REPOS` declares no `defaults`, so an unwired generic sits there waiting to drop a future
  // one SILENTLY. The guard fails loud instead, and this is the input that makes it fire.
  //
  // Why fail loud rather than wire repos defaults up: a repo name is caller-local BY DEFINITION, so a
  // std-shipped default repo name would bake consumer identity into the artifact (D4/NFR3) — the one
  // thing the reader block exists to prevent. The right answer to "I want a default repo" is "no",
  // stated by the code rather than left to a reviewer to notice.
  test("a repos-sourced `defaults` fails LOUD — the unwired half of estateDefaults (D4/NFR3)", () => {
    const mutated = JSON.parse(JSON.stringify(SURFACE)) as {
      commands: { flags?: { name: string; source?: string; defaults?: string[] }[]; subcommands: { flags: { name: string; source?: string; defaults?: string[] }[] }[] }[];
    };
    const repoFlags = mutated.commands
      .flatMap((c) => [...(c.flags ?? []), ...c.subcommands.flatMap((s) => s.flags)])
      .filter((f) => f.source === "estate.repos");
    // Positive control: the mutation has something to attach to. Without this, a SURFACE that stopped
    // declaring `source: "estate.repos"` would make the toThrow below pass for the wrong reason.
    expect(repoFlags.length).toBeGreaterThan(0);
    for (const f of repoFlags) f.defaults = ["std-owned-repo"];

    expect(() => generateStdCompletion(mutated as unknown as typeof SURFACE)).toThrow(RepoNavError);
    expect(() => generateStdCompletion(mutated as unknown as typeof SURFACE)).toThrow(/estate\.repos/);
    // And the unmutated surface does NOT throw — the guard is the mutation's doing, not a broken clone.
    const clean = JSON.parse(JSON.stringify(SURFACE)) as unknown as typeof SURFACE;
    expect(() => generateStdCompletion(clean)).not.toThrow();
  });
});

describe("escaping is a function with a hostile fixture, not a hopeful replace chain (AC4)", () => {
  // `' [ ] : \` and a backtick. The apostrophe is the one that bites on SHIPPED data today — `bmad
  // deploy`'s desc says "the estate's leg" and `cn verify`'s says "cn's declared plugin envelope" —
  // and an unescaped one does not merely look wrong, it makes the whole artifact fail to parse.
  const HOSTILE = "it's [bracketed] a:colon \\ and `tick`";

  test("a _describe entry escapes the apostrophe and leaves the description's colon alone", () => {
    const entry = describeEntry("deploy", HOSTILE);
    expect(entry).toContain("'\\''"); // the close-escape-reopen form
    expect(entry).not.toMatch(/[^\\']'[^\\']/); // no bare apostrophe left inside the word
    expect(entry).toContain("a:colon"); // only the FIRST colon splits an entry — do not escape it
  });

  test("a _describe completion NAME escapes a literal colon (man zshcompsys)", () => {
    // Every name in the surface is `[a-z]+` today, so this is future-proofing — asserted as such.
    for (const c of SURFACE.commands) {
      expect(c.name).toMatch(/^[a-z]+$/);
      for (const s of c.subcommands) expect(s.name).toMatch(/^[a-z]+$/);
    }
    expect(describeEntry("we:ird", "d")).toBe("'we\\:ird:d'");
  });

  test("an _arguments spec escapes brackets and backslash, and leaves the explanation's colon", () => {
    const spec = argSpec({ name: "--x", arity: "bool", desc: HOSTILE });
    expect(spec).toContain("\\[bracketed\\]"); // a bare `]` closes the explanation early
    expect(spec).toContain("a:colon"); // zsh's own _git ships `[add Signed-off-by: trailer …]`
    expect(spec).toContain("'\\''");
  });

  test.skipIf(!HAS_ZSH)("the escaped text ROUND-TRIPS through zsh exactly", async () => {
    const root = mkdtempSync(join(tmpdir(), "std-esc-"));
    try {
      const file = join(root, "t.zsh");
      writeFileSync(
        file,
        `local -a a\na=(${describeEntry("deploy", HOSTILE)} ${argSpec({ name: "--x", arity: "bool", desc: HOSTILE })})\nprint -r -- $a[1]\nprint -r -- $a[2]\n`,
      );
      const r = await spawnCapture("zsh", [file]);
      expect(r.code).toBe(0);
      const [entry, spec] = r.stdout.split("\n");
      expect(entry).toBe(`deploy:${HOSTILE}`); // the description survives byte-for-byte
      expect(spec).toBe("--x[it's \\[bracketed\\] a:colon \\\\ and `tick`]");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test.skipIf(!HAS_ZSH)("an UNESCAPED apostrophe would break the artifact — the red-turning input", async () => {
    const root = mkdtempSync(join(tmpdir(), "std-esc-"));
    try {
      const file = join(root, "bad.zsh");
      writeFileSync(file, `local -a a\na=('deploy:the estate's leg')\n`);
      const r = await spawnCapture("zsh", ["-n", file]);
      expect(r.code).toBe(1);
      expect(r.stderr).toContain("unmatched '");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});

describe("installAlias — deploy to targets, fail-loud writes nothing (AC1)", () => {
  test("writes both artifacts, creating parent dirs", () => {
    const root = mkdtempSync(join(tmpdir(), "std-install-"));
    try {
      const targets = defaultTargets(join(root, "zsh"));
      const res = installAlias({ config: cfg, surface: SURFACE, targets });
      expect(existsSync(res.repoNavPath)).toBe(true);
      expect(existsSync(res.completionPath)).toBe(true);
      expect(readFileSync(res.repoNavPath, "utf-8")).toContain("typeset -gA ZSH_REPOS=(");
      expect(readFileSync(res.completionPath, "utf-8")).toContain("#compdef std");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("a fail-loud registry writes NOTHING (validation precedes any write)", () => {
    const root = mkdtempSync(join(tmpdir(), "std-install-"));
    try {
      const targets = defaultTargets(join(root, "zsh"));
      expect(() =>
        installAlias({ config: { entries: { "bad name": "/x" } }, surface: SURFACE, targets }),
      ).toThrow(RepoNavError);
      // nothing was deployed
      expect(existsSync(join(root, "zsh"))).toBe(false);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("defaultTargets places artifacts under the ZDOTDIR functions/completions homes", () => {
    const t = defaultTargets("/x/.config/zsh");
    expect(t.repoNavPath).toBe("/x/.config/zsh/functions/repo-nav.zsh");
    expect(t.completionPath).toBe("/x/.config/zsh/completions/_std");
  });
});

describe("runAlias — the std-cli `alias` command (AC1)", () => {
  test("--install deploys and reports both paths, exit 0", () => {
    const root = mkdtempSync(join(tmpdir(), "std-alias-"));
    try {
      const lines: string[] = [];
      const code = runAlias(["--install"], {
        config: cfg,
        surface: SURFACE,
        targets: defaultTargets(join(root, "zsh")),
        log: (l) => lines.push(l),
      });
      expect(code).toBe(0);
      expect(lines.some((l) => l.includes("repo-nav.zsh"))).toBe(true);
      expect(lines.some((l) => l.includes("_std"))).toBe(true);
      expect(existsSync(join(root, "zsh", "functions", "repo-nav.zsh"))).toBe(true);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("a fail-loud registry returns exit 1 and writes nothing", () => {
    const root = mkdtempSync(join(tmpdir(), "std-alias-"));
    try {
      const code = runAlias(["--install"], {
        config: { entries: { "bad name": "/x" } },
        surface: SURFACE,
        targets: defaultTargets(join(root, "zsh")),
        log: () => {},
      });
      expect(code).toBe(1);
      expect(existsSync(join(root, "zsh"))).toBe(false);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("without --install prints usage, exit 2, deploys nothing", () => {
    const lines: string[] = [];
    const code = runAlias([], {
      config: cfg,
      surface: SURFACE,
      targets: defaultTargets("/should/not/be/written"),
      log: (l) => lines.push(l),
    });
    expect(code).toBe(2);
    expect(lines.join("\n")).toMatch(/usage: std alias --install/);
    expect(existsSync("/should/not/be/written")).toBe(false);
  });
});
